-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_write_outputs is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_fft_to_write_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    stream_fft_to_write_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_fft_to_write_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_fft_to_write_empty_n : IN STD_LOGIC;
    stream_fft_to_write_read : OUT STD_LOGIC;
    dout_data_0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_0_TVALID : OUT STD_LOGIC;
    dout_data_0_TREADY : IN STD_LOGIC;
    dout_data_1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_1_TVALID : OUT STD_LOGIC;
    dout_data_1_TREADY : IN STD_LOGIC;
    dout_data_2_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_2_TVALID : OUT STD_LOGIC;
    dout_data_2_TREADY : IN STD_LOGIC;
    dout_data_3_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_3_TVALID : OUT STD_LOGIC;
    dout_data_3_TREADY : IN STD_LOGIC );
end;


architecture behav of pfb_multichannel_write_outputs is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dummy_state : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_write_outputs_Pipeline_write_loop_fu_34_ap_start : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_ap_done : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_ap_idle : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_ap_ready : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TREADY : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TREADY : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TREADY : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TREADY : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TVALID : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TVALID : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TVALID : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TVALID : STD_LOGIC;
    signal grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call10 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln45_fu_52_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal regslice_both_dout_data_0_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_data_1_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_data_2_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_data_3_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal dout_data_0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_0_U_vld_out : STD_LOGIC;
    signal dout_data_1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_1_U_vld_out : STD_LOGIC;
    signal dout_data_2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_2_U_vld_out : STD_LOGIC;
    signal dout_data_3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_3_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_write_outputs_Pipeline_write_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_fft_to_write_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        stream_fft_to_write_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_fft_to_write_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_fft_to_write_empty_n : IN STD_LOGIC;
        stream_fft_to_write_read : OUT STD_LOGIC;
        dout_data_0_TREADY : IN STD_LOGIC;
        dout_data_1_TREADY : IN STD_LOGIC;
        dout_data_2_TREADY : IN STD_LOGIC;
        dout_data_3_TREADY : IN STD_LOGIC;
        dout_data_0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_data_0_TVALID : OUT STD_LOGIC;
        dout_data_1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_data_1_TVALID : OUT STD_LOGIC;
        dout_data_2_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_data_2_TVALID : OUT STD_LOGIC;
        dout_data_3_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        dout_data_3_TVALID : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_write_outputs_Pipeline_write_loop_fu_34 : component pfb_multichannel_write_outputs_Pipeline_write_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_outputs_Pipeline_write_loop_fu_34_ap_start,
        ap_done => grp_write_outputs_Pipeline_write_loop_fu_34_ap_done,
        ap_idle => grp_write_outputs_Pipeline_write_loop_fu_34_ap_idle,
        ap_ready => grp_write_outputs_Pipeline_write_loop_fu_34_ap_ready,
        stream_fft_to_write_dout => stream_fft_to_write_dout,
        stream_fft_to_write_num_data_valid => ap_const_lv5_0,
        stream_fft_to_write_fifo_cap => ap_const_lv5_0,
        stream_fft_to_write_empty_n => stream_fft_to_write_empty_n,
        stream_fft_to_write_read => grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read,
        dout_data_0_TREADY => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TREADY,
        dout_data_1_TREADY => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TREADY,
        dout_data_2_TREADY => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TREADY,
        dout_data_3_TREADY => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TREADY,
        dout_data_0_TDATA => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TDATA,
        dout_data_0_TVALID => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TVALID,
        dout_data_1_TDATA => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TDATA,
        dout_data_1_TVALID => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TVALID,
        dout_data_2_TDATA => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TDATA,
        dout_data_2_TVALID => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TVALID,
        dout_data_3_TDATA => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TDATA,
        dout_data_3_TVALID => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TVALID);

    regslice_both_dout_data_0_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TDATA,
        vld_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TVALID,
        ack_in => dout_data_0_TREADY_int_regslice,
        data_out => dout_data_0_TDATA,
        vld_out => regslice_both_dout_data_0_U_vld_out,
        ack_out => dout_data_0_TREADY,
        apdone_blk => regslice_both_dout_data_0_U_apdone_blk);

    regslice_both_dout_data_1_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TDATA,
        vld_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TVALID,
        ack_in => dout_data_1_TREADY_int_regslice,
        data_out => dout_data_1_TDATA,
        vld_out => regslice_both_dout_data_1_U_vld_out,
        ack_out => dout_data_1_TREADY,
        apdone_blk => regslice_both_dout_data_1_U_apdone_blk);

    regslice_both_dout_data_2_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TDATA,
        vld_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TVALID,
        ack_in => dout_data_2_TREADY_int_regslice,
        data_out => dout_data_2_TDATA,
        vld_out => regslice_both_dout_data_2_U_vld_out,
        ack_out => dout_data_2_TREADY,
        apdone_blk => regslice_both_dout_data_2_U_apdone_blk);

    regslice_both_dout_data_3_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TDATA,
        vld_in => grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TVALID,
        ack_in => dout_data_3_TREADY_int_regslice,
        data_out => dout_data_3_TDATA,
        vld_out => regslice_both_dout_data_3_U_vld_out,
        ack_out => dout_data_3_TREADY,
        apdone_blk => regslice_both_dout_data_3_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call10) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_outputs_Pipeline_write_loop_fu_34_ap_ready = ap_const_logic_1)) then 
                    grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                dummy_state <= add_ln45_fu_52_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, grp_write_outputs_Pipeline_write_loop_fu_34_ap_done, ap_CS_fsm_state2, ap_block_state1, ap_CS_fsm_state3, ap_block_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_write_outputs_Pipeline_write_loop_fu_34_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln45_fu_52_p2 <= std_logic_vector(unsigned(dummy_state) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_write_outputs_Pipeline_write_loop_fu_34_ap_done)
    begin
        if ((grp_write_outputs_Pipeline_write_loop_fu_34_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call10_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call10 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(regslice_both_dout_data_0_U_apdone_blk, regslice_both_dout_data_1_U_apdone_blk, regslice_both_dout_data_2_U_apdone_blk, regslice_both_dout_data_3_U_apdone_blk)
    begin
                ap_block_state3 <= ((regslice_both_dout_data_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_0_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    dout_data_0_TVALID <= regslice_both_dout_data_0_U_vld_out;
    dout_data_1_TVALID <= regslice_both_dout_data_1_U_vld_out;
    dout_data_2_TVALID <= regslice_both_dout_data_2_U_vld_out;
    dout_data_3_TVALID <= regslice_both_dout_data_3_U_vld_out;
    grp_write_outputs_Pipeline_write_loop_fu_34_ap_start <= grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg;
    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TREADY <= (dout_data_0_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TREADY <= (dout_data_1_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TREADY <= (dout_data_2_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TREADY <= (dout_data_3_TREADY_int_regslice and ap_CS_fsm_state2);

    stream_fft_to_write_read_assign_proc : process(grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            stream_fft_to_write_read <= grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read;
        else 
            stream_fft_to_write_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
