-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_repack_Pipeline_repack_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ch0_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ch0_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    ch0_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    ch0_out_empty_n : IN STD_LOGIC;
    ch0_out_read : OUT STD_LOGIC;
    ch1_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ch1_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    ch1_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    ch1_out_empty_n : IN STD_LOGIC;
    ch1_out_read : OUT STD_LOGIC;
    ch2_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ch2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    ch2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    ch2_out_empty_n : IN STD_LOGIC;
    ch2_out_read : OUT STD_LOGIC;
    ch3_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ch3_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    ch3_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    ch3_out_empty_n : IN STD_LOGIC;
    ch3_out_read : OUT STD_LOGIC;
    stream_fft_to_write_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    stream_fft_to_write_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_fft_to_write_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_fft_to_write_full_n : IN STD_LOGIC;
    stream_fft_to_write_write : OUT STD_LOGIC );
end;


architecture behav of pfb_multichannel_repack_Pipeline_repack_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_8001 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln109_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ch0_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ch1_out_blk_n : STD_LOGIC;
    signal ch2_out_blk_n : STD_LOGIC;
    signal ch3_out_blk_n : STD_LOGIC;
    signal stream_fft_to_write_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal out_pack_i_fu_204_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_reg_498 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_fu_244_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_reg_503 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_1_fu_278_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_1_reg_508 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_1_fu_318_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_1_reg_513 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_2_fu_352_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_2_reg_518 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_2_fu_392_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_2_reg_523 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_3_fu_426_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_i_3_reg_528 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_3_fu_466_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_pack_q_3_reg_533 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_fu_62 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal i_6_fu_111_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln118_fu_186_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln118_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val0_M_real_fu_122_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_178_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln118_fu_196_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_220_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln118_1_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val0_M_imag_fu_126_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_212_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln118_1_fu_236_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln119_fu_260_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln119_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val1_M_real_fu_136_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln119_fu_270_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_294_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln119_1_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val1_M_imag_fu_140_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_286_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln119_1_fu_310_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln120_fu_334_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln120_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val2_M_real_fu_150_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_326_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln120_fu_344_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_368_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln120_1_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val2_M_imag_fu_154_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_360_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln120_1_fu_384_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln121_fu_408_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln121_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val3_M_real_fu_164_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_400_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln121_fu_418_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_442_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln121_1_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val3_M_imag_fu_168_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_434_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln121_1_fu_458_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pfb_multichannel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_105_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_62 <= i_6_fu_111_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_62 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                out_pack_i_1_reg_508 <= out_pack_i_1_fu_278_p3;
                out_pack_i_2_reg_518 <= out_pack_i_2_fu_352_p3;
                out_pack_i_3_reg_528 <= out_pack_i_3_fu_426_p3;
                out_pack_i_reg_498 <= out_pack_i_fu_204_p3;
                out_pack_q_1_reg_513 <= out_pack_q_1_fu_318_p3;
                out_pack_q_2_reg_523 <= out_pack_q_2_fu_392_p3;
                out_pack_q_3_reg_533 <= out_pack_q_3_fu_466_p3;
                out_pack_q_reg_503 <= out_pack_q_fu_244_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(ch0_out_empty_n, ch1_out_empty_n, ch2_out_empty_n, ch3_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ch3_out_empty_n = ap_const_logic_0) or (ch2_out_empty_n = ap_const_logic_0) or (ch1_out_empty_n = ap_const_logic_0) or (ch0_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(stream_fft_to_write_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (stream_fft_to_write_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln109_fu_105_p2)
    begin
        if (((icmp_ln109_fu_105_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_62, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_62;
        end if; 
    end process;


    ch0_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ch0_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch0_out_blk_n <= ch0_out_empty_n;
        else 
            ch0_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ch0_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch0_out_read <= ap_const_logic_1;
        else 
            ch0_out_read <= ap_const_logic_0;
        end if; 
    end process;


    ch1_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ch1_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch1_out_blk_n <= ch1_out_empty_n;
        else 
            ch1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ch1_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch1_out_read <= ap_const_logic_1;
        else 
            ch1_out_read <= ap_const_logic_0;
        end if; 
    end process;


    ch2_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ch2_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch2_out_blk_n <= ch2_out_empty_n;
        else 
            ch2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ch2_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch2_out_read <= ap_const_logic_1;
        else 
            ch2_out_read <= ap_const_logic_0;
        end if; 
    end process;


    ch3_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ch3_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch3_out_blk_n <= ch3_out_empty_n;
        else 
            ch3_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ch3_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ch3_out_read <= ap_const_logic_1;
        else 
            ch3_out_read <= ap_const_logic_0;
        end if; 
    end process;

    i_6_fu_111_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv11_1));
    icmp_ln109_fu_105_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv11_400) else "0";
    icmp_ln118_1_fu_230_p2 <= "1" when (tmp_4_fu_220_p4 = ap_const_lv15_0) else "0";
    icmp_ln118_fu_190_p2 <= "1" when (trunc_ln118_fu_186_p1 = ap_const_lv15_0) else "0";
    icmp_ln119_1_fu_304_p2 <= "1" when (tmp_6_fu_294_p4 = ap_const_lv15_0) else "0";
    icmp_ln119_fu_264_p2 <= "1" when (trunc_ln119_fu_260_p1 = ap_const_lv15_0) else "0";
    icmp_ln120_1_fu_378_p2 <= "1" when (tmp_8_fu_368_p4 = ap_const_lv15_0) else "0";
    icmp_ln120_fu_338_p2 <= "1" when (trunc_ln120_fu_334_p1 = ap_const_lv15_0) else "0";
    icmp_ln121_1_fu_452_p2 <= "1" when (tmp_1_fu_442_p4 = ap_const_lv15_0) else "0";
    icmp_ln121_fu_412_p2 <= "1" when (trunc_ln121_fu_408_p1 = ap_const_lv15_0) else "0";
    out_pack_i_1_fu_278_p3 <= 
        select_ln119_fu_270_p3 when (tmp_3_fu_252_p3(0) = '1') else 
        val1_M_real_fu_136_p1;
    out_pack_i_2_fu_352_p3 <= 
        select_ln120_fu_344_p3 when (tmp_7_fu_326_p3(0) = '1') else 
        val2_M_real_fu_150_p1;
    out_pack_i_3_fu_426_p3 <= 
        select_ln121_fu_418_p3 when (tmp_10_fu_400_p3(0) = '1') else 
        val3_M_real_fu_164_p1;
    out_pack_i_fu_204_p3 <= 
        select_ln118_fu_196_p3 when (tmp_fu_178_p3(0) = '1') else 
        val0_M_real_fu_122_p1;
    out_pack_q_1_fu_318_p3 <= 
        select_ln119_1_fu_310_p3 when (tmp_5_fu_286_p3(0) = '1') else 
        val1_M_imag_fu_140_p4;
    out_pack_q_2_fu_392_p3 <= 
        select_ln120_1_fu_384_p3 when (tmp_9_fu_360_p3(0) = '1') else 
        val2_M_imag_fu_154_p4;
    out_pack_q_3_fu_466_p3 <= 
        select_ln121_1_fu_458_p3 when (tmp_11_fu_434_p3(0) = '1') else 
        val3_M_imag_fu_168_p4;
    out_pack_q_fu_244_p3 <= 
        select_ln118_1_fu_236_p3 when (tmp_2_fu_212_p3(0) = '1') else 
        val0_M_imag_fu_126_p4;
    select_ln118_1_fu_236_p3 <= 
        ap_const_lv16_8001 when (icmp_ln118_1_fu_230_p2(0) = '1') else 
        val0_M_imag_fu_126_p4;
    select_ln118_fu_196_p3 <= 
        ap_const_lv16_8001 when (icmp_ln118_fu_190_p2(0) = '1') else 
        val0_M_real_fu_122_p1;
    select_ln119_1_fu_310_p3 <= 
        ap_const_lv16_8001 when (icmp_ln119_1_fu_304_p2(0) = '1') else 
        val1_M_imag_fu_140_p4;
    select_ln119_fu_270_p3 <= 
        ap_const_lv16_8001 when (icmp_ln119_fu_264_p2(0) = '1') else 
        val1_M_real_fu_136_p1;
    select_ln120_1_fu_384_p3 <= 
        ap_const_lv16_8001 when (icmp_ln120_1_fu_378_p2(0) = '1') else 
        val2_M_imag_fu_154_p4;
    select_ln120_fu_344_p3 <= 
        ap_const_lv16_8001 when (icmp_ln120_fu_338_p2(0) = '1') else 
        val2_M_real_fu_150_p1;
    select_ln121_1_fu_458_p3 <= 
        ap_const_lv16_8001 when (icmp_ln121_1_fu_452_p2(0) = '1') else 
        val3_M_imag_fu_168_p4;
    select_ln121_fu_418_p3 <= 
        ap_const_lv16_8001 when (icmp_ln121_fu_412_p2(0) = '1') else 
        val3_M_real_fu_164_p1;

    stream_fft_to_write_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, stream_fft_to_write_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            stream_fft_to_write_blk_n <= stream_fft_to_write_full_n;
        else 
            stream_fft_to_write_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_fft_to_write_din <= (((((((out_pack_q_3_reg_533 & out_pack_i_3_reg_528) & out_pack_q_2_reg_523) & out_pack_i_2_reg_518) & out_pack_q_1_reg_513) & out_pack_i_1_reg_508) & out_pack_q_reg_503) & out_pack_i_reg_498);

    stream_fft_to_write_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            stream_fft_to_write_write <= ap_const_logic_1;
        else 
            stream_fft_to_write_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_400_p3 <= ch3_out_dout(15 downto 15);
    tmp_11_fu_434_p3 <= ch3_out_dout(31 downto 31);
    tmp_1_fu_442_p4 <= ch3_out_dout(30 downto 16);
    tmp_2_fu_212_p3 <= ch0_out_dout(31 downto 31);
    tmp_3_fu_252_p3 <= ch1_out_dout(15 downto 15);
    tmp_4_fu_220_p4 <= ch0_out_dout(30 downto 16);
    tmp_5_fu_286_p3 <= ch1_out_dout(31 downto 31);
    tmp_6_fu_294_p4 <= ch1_out_dout(30 downto 16);
    tmp_7_fu_326_p3 <= ch2_out_dout(15 downto 15);
    tmp_8_fu_368_p4 <= ch2_out_dout(30 downto 16);
    tmp_9_fu_360_p3 <= ch2_out_dout(31 downto 31);
    tmp_fu_178_p3 <= ch0_out_dout(15 downto 15);
    trunc_ln118_fu_186_p1 <= ch0_out_dout(15 - 1 downto 0);
    trunc_ln119_fu_260_p1 <= ch1_out_dout(15 - 1 downto 0);
    trunc_ln120_fu_334_p1 <= ch2_out_dout(15 - 1 downto 0);
    trunc_ln121_fu_408_p1 <= ch3_out_dout(15 - 1 downto 0);
    val0_M_imag_fu_126_p4 <= ch0_out_dout(31 downto 16);
    val0_M_real_fu_122_p1 <= ch0_out_dout(16 - 1 downto 0);
    val1_M_imag_fu_140_p4 <= ch1_out_dout(31 downto 16);
    val1_M_real_fu_136_p1 <= ch1_out_dout(16 - 1 downto 0);
    val2_M_imag_fu_154_p4 <= ch2_out_dout(31 downto 16);
    val2_M_real_fu_150_p1 <= ch2_out_dout(16 - 1 downto 0);
    val3_M_imag_fu_168_p4 <= ch3_out_dout(31 downto 16);
    val3_M_real_fu_164_p1 <= ch3_out_dout(16 - 1 downto 0);
end behav;
