-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_fft is
port (
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    stream_compute_to_fft_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    stream_compute_to_fft_empty_n : IN STD_LOGIC;
    stream_compute_to_fft_read : OUT STD_LOGIC;
    stream_fft_to_write_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    stream_fft_to_write_full_n : IN STD_LOGIC;
    stream_fft_to_write_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of pfb_multichannel_fft is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal internal_ap_ready : STD_LOGIC;
    signal init_fft_config_U0_ap_start : STD_LOGIC;
    signal init_fft_config_U0_start_full_n : STD_LOGIC;
    signal init_fft_config_U0_ap_done : STD_LOGIC;
    signal init_fft_config_U0_ap_continue : STD_LOGIC;
    signal init_fft_config_U0_ap_idle : STD_LOGIC;
    signal init_fft_config_U0_ap_ready : STD_LOGIC;
    signal init_fft_config_U0_start_out : STD_LOGIC;
    signal init_fft_config_U0_start_write : STD_LOGIC;
    signal init_fft_config_U0_cfg0_s_din : STD_LOGIC_VECTOR (15 downto 0);
    signal init_fft_config_U0_cfg0_s_write : STD_LOGIC;
    signal init_fft_config_U0_cfg1_s_din : STD_LOGIC_VECTOR (15 downto 0);
    signal init_fft_config_U0_cfg1_s_write : STD_LOGIC;
    signal init_fft_config_U0_cfg2_s_din : STD_LOGIC_VECTOR (15 downto 0);
    signal init_fft_config_U0_cfg2_s_write : STD_LOGIC;
    signal init_fft_config_U0_cfg3_s_din : STD_LOGIC_VECTOR (15 downto 0);
    signal init_fft_config_U0_cfg3_s_write : STD_LOGIC;
    signal unpack_U0_ap_start : STD_LOGIC;
    signal unpack_U0_ap_done : STD_LOGIC;
    signal unpack_U0_ap_continue : STD_LOGIC;
    signal unpack_U0_ap_idle : STD_LOGIC;
    signal unpack_U0_ap_ready : STD_LOGIC;
    signal unpack_U0_stream_compute_to_fft_read : STD_LOGIC;
    signal unpack_U0_ch0_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal unpack_U0_ch0_in_write : STD_LOGIC;
    signal unpack_U0_ch1_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal unpack_U0_ch1_in_write : STD_LOGIC;
    signal unpack_U0_ch2_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal unpack_U0_ch2_in_write : STD_LOGIC;
    signal unpack_U0_ch3_in_din : STD_LOGIC_VECTOR (31 downto 0);
    signal unpack_U0_ch3_in_write : STD_LOGIC;
    signal fft_config1_1_U0_ch0_in_read : STD_LOGIC;
    signal fft_config1_1_U0_ch0_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_config1_1_U0_ch0_out_write : STD_LOGIC;
    signal fft_config1_1_U0_stat0_s_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_config1_1_U0_stat0_s_write : STD_LOGIC;
    signal fft_config1_1_U0_cfg0_s_read : STD_LOGIC;
    signal fft_config1_1_U0_ap_ready : STD_LOGIC;
    signal fft_config1_2_U0_ch1_in_read : STD_LOGIC;
    signal fft_config1_2_U0_ch1_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_config1_2_U0_ch1_out_write : STD_LOGIC;
    signal fft_config1_2_U0_stat1_s_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_config1_2_U0_stat1_s_write : STD_LOGIC;
    signal fft_config1_2_U0_cfg1_s_read : STD_LOGIC;
    signal fft_config1_2_U0_ap_ready : STD_LOGIC;
    signal fft_config1_3_U0_ch2_in_read : STD_LOGIC;
    signal fft_config1_3_U0_ch2_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_config1_3_U0_ch2_out_write : STD_LOGIC;
    signal fft_config1_3_U0_stat2_s_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_config1_3_U0_stat2_s_write : STD_LOGIC;
    signal fft_config1_3_U0_cfg2_s_read : STD_LOGIC;
    signal fft_config1_3_U0_ap_ready : STD_LOGIC;
    signal fft_config1_U0_ch3_in_read : STD_LOGIC;
    signal fft_config1_U0_ch3_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_config1_U0_ch3_out_write : STD_LOGIC;
    signal fft_config1_U0_stat3_s_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_config1_U0_stat3_s_write : STD_LOGIC;
    signal fft_config1_U0_cfg3_s_read : STD_LOGIC;
    signal fft_config1_U0_ap_ready : STD_LOGIC;
    signal repack_U0_ap_start : STD_LOGIC;
    signal repack_U0_ap_done : STD_LOGIC;
    signal repack_U0_ap_continue : STD_LOGIC;
    signal repack_U0_ap_idle : STD_LOGIC;
    signal repack_U0_ap_ready : STD_LOGIC;
    signal repack_U0_ch0_out_read : STD_LOGIC;
    signal repack_U0_ch1_out_read : STD_LOGIC;
    signal repack_U0_ch2_out_read : STD_LOGIC;
    signal repack_U0_ch3_out_read : STD_LOGIC;
    signal repack_U0_stream_fft_to_write_din : STD_LOGIC_VECTOR (127 downto 0);
    signal repack_U0_stream_fft_to_write_write : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal capture_status_U0_ap_start : STD_LOGIC;
    signal capture_status_U0_ap_done : STD_LOGIC;
    signal capture_status_U0_ap_continue : STD_LOGIC;
    signal capture_status_U0_ap_idle : STD_LOGIC;
    signal capture_status_U0_ap_ready : STD_LOGIC;
    signal capture_status_U0_stat0_s_read : STD_LOGIC;
    signal capture_status_U0_stat1_s_read : STD_LOGIC;
    signal capture_status_U0_stat2_s_read : STD_LOGIC;
    signal capture_status_U0_stat3_s_read : STD_LOGIC;
    signal cfg0_s_full_n : STD_LOGIC;
    signal cfg0_s_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal cfg0_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg0_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg0_s_empty_n : STD_LOGIC;
    signal cfg1_s_full_n : STD_LOGIC;
    signal cfg1_s_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal cfg1_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg1_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg1_s_empty_n : STD_LOGIC;
    signal cfg2_s_full_n : STD_LOGIC;
    signal cfg2_s_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal cfg2_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg2_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg2_s_empty_n : STD_LOGIC;
    signal cfg3_s_full_n : STD_LOGIC;
    signal cfg3_s_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal cfg3_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg3_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal cfg3_s_empty_n : STD_LOGIC;
    signal ch0_in_full_n : STD_LOGIC;
    signal ch0_in_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch0_in_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch0_in_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch0_in_empty_n : STD_LOGIC;
    signal ch1_in_full_n : STD_LOGIC;
    signal ch1_in_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch1_in_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch1_in_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch1_in_empty_n : STD_LOGIC;
    signal ch2_in_full_n : STD_LOGIC;
    signal ch2_in_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch2_in_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch2_in_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch2_in_empty_n : STD_LOGIC;
    signal ch3_in_full_n : STD_LOGIC;
    signal ch3_in_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch3_in_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch3_in_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch3_in_empty_n : STD_LOGIC;
    signal ch0_out_full_n : STD_LOGIC;
    signal ch0_out_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch0_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch0_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch0_out_empty_n : STD_LOGIC;
    signal stat0_s_full_n : STD_LOGIC;
    signal stat0_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stat0_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal stat0_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal stat0_s_empty_n : STD_LOGIC;
    signal ch1_out_full_n : STD_LOGIC;
    signal ch1_out_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch1_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch1_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch1_out_empty_n : STD_LOGIC;
    signal stat1_s_full_n : STD_LOGIC;
    signal stat1_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stat1_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal stat1_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal stat1_s_empty_n : STD_LOGIC;
    signal ch2_out_full_n : STD_LOGIC;
    signal ch2_out_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch2_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch2_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch2_out_empty_n : STD_LOGIC;
    signal stat2_s_full_n : STD_LOGIC;
    signal stat2_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stat2_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal stat2_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal stat2_s_empty_n : STD_LOGIC;
    signal ch3_out_full_n : STD_LOGIC;
    signal ch3_out_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal ch3_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal ch3_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal ch3_out_empty_n : STD_LOGIC;
    signal stat3_s_full_n : STD_LOGIC;
    signal stat3_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stat3_s_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal stat3_s_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal stat3_s_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_init_fft_config_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_init_fft_config_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_unpack_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_unpack_U0_ap_ready : STD_LOGIC;
    signal start_for_repack_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_repack_U0_full_n : STD_LOGIC;
    signal start_for_repack_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_repack_U0_empty_n : STD_LOGIC;
    signal start_for_capture_status_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_capture_status_U0_full_n : STD_LOGIC;
    signal start_for_capture_status_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_capture_status_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_init_fft_config IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        cfg0_s_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        cfg0_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg0_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg0_s_full_n : IN STD_LOGIC;
        cfg0_s_write : OUT STD_LOGIC;
        cfg1_s_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        cfg1_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg1_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg1_s_full_n : IN STD_LOGIC;
        cfg1_s_write : OUT STD_LOGIC;
        cfg2_s_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        cfg2_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg2_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg2_s_full_n : IN STD_LOGIC;
        cfg2_s_write : OUT STD_LOGIC;
        cfg3_s_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        cfg3_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg3_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        cfg3_s_full_n : IN STD_LOGIC;
        cfg3_s_write : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_unpack IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_compute_to_fft_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        stream_compute_to_fft_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_compute_to_fft_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_compute_to_fft_empty_n : IN STD_LOGIC;
        stream_compute_to_fft_read : OUT STD_LOGIC;
        ch0_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch0_in_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch0_in_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch0_in_full_n : IN STD_LOGIC;
        ch0_in_write : OUT STD_LOGIC;
        ch1_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch1_in_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch1_in_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch1_in_full_n : IN STD_LOGIC;
        ch1_in_write : OUT STD_LOGIC;
        ch2_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch2_in_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch2_in_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch2_in_full_n : IN STD_LOGIC;
        ch2_in_write : OUT STD_LOGIC;
        ch3_in_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch3_in_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch3_in_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch3_in_full_n : IN STD_LOGIC;
        ch3_in_write : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_fft_config1_1 IS
    port (
        ch0_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch0_in_empty_n : IN STD_LOGIC;
        ch0_in_read : OUT STD_LOGIC;
        ch0_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch0_out_full_n : IN STD_LOGIC;
        ch0_out_write : OUT STD_LOGIC;
        stat0_s_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stat0_s_full_n : IN STD_LOGIC;
        stat0_s_write : OUT STD_LOGIC;
        cfg0_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        cfg0_s_empty_n : IN STD_LOGIC;
        cfg0_s_read : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_fft_config1_2 IS
    port (
        ch1_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch1_in_empty_n : IN STD_LOGIC;
        ch1_in_read : OUT STD_LOGIC;
        ch1_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch1_out_full_n : IN STD_LOGIC;
        ch1_out_write : OUT STD_LOGIC;
        stat1_s_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stat1_s_full_n : IN STD_LOGIC;
        stat1_s_write : OUT STD_LOGIC;
        cfg1_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        cfg1_s_empty_n : IN STD_LOGIC;
        cfg1_s_read : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_fft_config1_3 IS
    port (
        ch2_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch2_in_empty_n : IN STD_LOGIC;
        ch2_in_read : OUT STD_LOGIC;
        ch2_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch2_out_full_n : IN STD_LOGIC;
        ch2_out_write : OUT STD_LOGIC;
        stat2_s_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stat2_s_full_n : IN STD_LOGIC;
        stat2_s_write : OUT STD_LOGIC;
        cfg2_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        cfg2_s_empty_n : IN STD_LOGIC;
        cfg2_s_read : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_fft_config1_s IS
    port (
        ch3_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch3_in_empty_n : IN STD_LOGIC;
        ch3_in_read : OUT STD_LOGIC;
        ch3_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ch3_out_full_n : IN STD_LOGIC;
        ch3_out_write : OUT STD_LOGIC;
        stat3_s_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stat3_s_full_n : IN STD_LOGIC;
        stat3_s_write : OUT STD_LOGIC;
        cfg3_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        cfg3_s_empty_n : IN STD_LOGIC;
        cfg3_s_read : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_repack IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ch0_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch0_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch0_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch0_out_empty_n : IN STD_LOGIC;
        ch0_out_read : OUT STD_LOGIC;
        ch1_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch1_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch1_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch1_out_empty_n : IN STD_LOGIC;
        ch1_out_read : OUT STD_LOGIC;
        ch2_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch2_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch2_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch2_out_empty_n : IN STD_LOGIC;
        ch2_out_read : OUT STD_LOGIC;
        ch3_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ch3_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        ch3_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        ch3_out_empty_n : IN STD_LOGIC;
        ch3_out_read : OUT STD_LOGIC;
        stream_fft_to_write_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        stream_fft_to_write_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_fft_to_write_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_fft_to_write_full_n : IN STD_LOGIC;
        stream_fft_to_write_write : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_capture_status IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stat0_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stat0_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stat0_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stat0_s_empty_n : IN STD_LOGIC;
        stat0_s_read : OUT STD_LOGIC;
        stat1_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stat1_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stat1_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stat1_s_empty_n : IN STD_LOGIC;
        stat1_s_read : OUT STD_LOGIC;
        stat2_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stat2_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stat2_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stat2_s_empty_n : IN STD_LOGIC;
        stat2_s_read : OUT STD_LOGIC;
        stat3_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stat3_s_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stat3_s_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stat3_s_empty_n : IN STD_LOGIC;
        stat3_s_read : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pfb_multichannel_fifo_w32_d1024_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pfb_multichannel_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pfb_multichannel_start_for_repack_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component pfb_multichannel_start_for_capture_status_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    init_fft_config_U0 : component pfb_multichannel_init_fft_config
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => init_fft_config_U0_ap_start,
        start_full_n => init_fft_config_U0_start_full_n,
        ap_done => init_fft_config_U0_ap_done,
        ap_continue => init_fft_config_U0_ap_continue,
        ap_idle => init_fft_config_U0_ap_idle,
        ap_ready => init_fft_config_U0_ap_ready,
        start_out => init_fft_config_U0_start_out,
        start_write => init_fft_config_U0_start_write,
        cfg0_s_din => init_fft_config_U0_cfg0_s_din,
        cfg0_s_num_data_valid => cfg0_s_num_data_valid,
        cfg0_s_fifo_cap => cfg0_s_fifo_cap,
        cfg0_s_full_n => cfg0_s_full_n,
        cfg0_s_write => init_fft_config_U0_cfg0_s_write,
        cfg1_s_din => init_fft_config_U0_cfg1_s_din,
        cfg1_s_num_data_valid => cfg1_s_num_data_valid,
        cfg1_s_fifo_cap => cfg1_s_fifo_cap,
        cfg1_s_full_n => cfg1_s_full_n,
        cfg1_s_write => init_fft_config_U0_cfg1_s_write,
        cfg2_s_din => init_fft_config_U0_cfg2_s_din,
        cfg2_s_num_data_valid => cfg2_s_num_data_valid,
        cfg2_s_fifo_cap => cfg2_s_fifo_cap,
        cfg2_s_full_n => cfg2_s_full_n,
        cfg2_s_write => init_fft_config_U0_cfg2_s_write,
        cfg3_s_din => init_fft_config_U0_cfg3_s_din,
        cfg3_s_num_data_valid => cfg3_s_num_data_valid,
        cfg3_s_fifo_cap => cfg3_s_fifo_cap,
        cfg3_s_full_n => cfg3_s_full_n,
        cfg3_s_write => init_fft_config_U0_cfg3_s_write);

    unpack_U0 : component pfb_multichannel_unpack
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => unpack_U0_ap_start,
        ap_done => unpack_U0_ap_done,
        ap_continue => unpack_U0_ap_continue,
        ap_idle => unpack_U0_ap_idle,
        ap_ready => unpack_U0_ap_ready,
        stream_compute_to_fft_dout => stream_compute_to_fft_dout,
        stream_compute_to_fft_num_data_valid => ap_const_lv5_0,
        stream_compute_to_fft_fifo_cap => ap_const_lv5_0,
        stream_compute_to_fft_empty_n => stream_compute_to_fft_empty_n,
        stream_compute_to_fft_read => unpack_U0_stream_compute_to_fft_read,
        ch0_in_din => unpack_U0_ch0_in_din,
        ch0_in_num_data_valid => ch0_in_num_data_valid,
        ch0_in_fifo_cap => ch0_in_fifo_cap,
        ch0_in_full_n => ch0_in_full_n,
        ch0_in_write => unpack_U0_ch0_in_write,
        ch1_in_din => unpack_U0_ch1_in_din,
        ch1_in_num_data_valid => ch1_in_num_data_valid,
        ch1_in_fifo_cap => ch1_in_fifo_cap,
        ch1_in_full_n => ch1_in_full_n,
        ch1_in_write => unpack_U0_ch1_in_write,
        ch2_in_din => unpack_U0_ch2_in_din,
        ch2_in_num_data_valid => ch2_in_num_data_valid,
        ch2_in_fifo_cap => ch2_in_fifo_cap,
        ch2_in_full_n => ch2_in_full_n,
        ch2_in_write => unpack_U0_ch2_in_write,
        ch3_in_din => unpack_U0_ch3_in_din,
        ch3_in_num_data_valid => ch3_in_num_data_valid,
        ch3_in_fifo_cap => ch3_in_fifo_cap,
        ch3_in_full_n => ch3_in_full_n,
        ch3_in_write => unpack_U0_ch3_in_write);

    fft_config1_1_U0 : component pfb_multichannel_fft_config1_1
    port map (
        ch0_in_dout => ch0_in_dout,
        ch0_in_empty_n => ch0_in_empty_n,
        ch0_in_read => fft_config1_1_U0_ch0_in_read,
        ch0_out_din => fft_config1_1_U0_ch0_out_din,
        ch0_out_full_n => ch0_out_full_n,
        ch0_out_write => fft_config1_1_U0_ch0_out_write,
        stat0_s_din => fft_config1_1_U0_stat0_s_din,
        stat0_s_full_n => stat0_s_full_n,
        stat0_s_write => fft_config1_1_U0_stat0_s_write,
        cfg0_s_dout => cfg0_s_dout,
        cfg0_s_empty_n => cfg0_s_empty_n,
        cfg0_s_read => fft_config1_1_U0_cfg0_s_read,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ready => fft_config1_1_U0_ap_ready);

    fft_config1_2_U0 : component pfb_multichannel_fft_config1_2
    port map (
        ch1_in_dout => ch1_in_dout,
        ch1_in_empty_n => ch1_in_empty_n,
        ch1_in_read => fft_config1_2_U0_ch1_in_read,
        ch1_out_din => fft_config1_2_U0_ch1_out_din,
        ch1_out_full_n => ch1_out_full_n,
        ch1_out_write => fft_config1_2_U0_ch1_out_write,
        stat1_s_din => fft_config1_2_U0_stat1_s_din,
        stat1_s_full_n => stat1_s_full_n,
        stat1_s_write => fft_config1_2_U0_stat1_s_write,
        cfg1_s_dout => cfg1_s_dout,
        cfg1_s_empty_n => cfg1_s_empty_n,
        cfg1_s_read => fft_config1_2_U0_cfg1_s_read,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ready => fft_config1_2_U0_ap_ready);

    fft_config1_3_U0 : component pfb_multichannel_fft_config1_3
    port map (
        ch2_in_dout => ch2_in_dout,
        ch2_in_empty_n => ch2_in_empty_n,
        ch2_in_read => fft_config1_3_U0_ch2_in_read,
        ch2_out_din => fft_config1_3_U0_ch2_out_din,
        ch2_out_full_n => ch2_out_full_n,
        ch2_out_write => fft_config1_3_U0_ch2_out_write,
        stat2_s_din => fft_config1_3_U0_stat2_s_din,
        stat2_s_full_n => stat2_s_full_n,
        stat2_s_write => fft_config1_3_U0_stat2_s_write,
        cfg2_s_dout => cfg2_s_dout,
        cfg2_s_empty_n => cfg2_s_empty_n,
        cfg2_s_read => fft_config1_3_U0_cfg2_s_read,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ready => fft_config1_3_U0_ap_ready);

    fft_config1_U0 : component pfb_multichannel_fft_config1_s
    port map (
        ch3_in_dout => ch3_in_dout,
        ch3_in_empty_n => ch3_in_empty_n,
        ch3_in_read => fft_config1_U0_ch3_in_read,
        ch3_out_din => fft_config1_U0_ch3_out_din,
        ch3_out_full_n => ch3_out_full_n,
        ch3_out_write => fft_config1_U0_ch3_out_write,
        stat3_s_din => fft_config1_U0_stat3_s_din,
        stat3_s_full_n => stat3_s_full_n,
        stat3_s_write => fft_config1_U0_stat3_s_write,
        cfg3_s_dout => cfg3_s_dout,
        cfg3_s_empty_n => cfg3_s_empty_n,
        cfg3_s_read => fft_config1_U0_cfg3_s_read,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ready => fft_config1_U0_ap_ready);

    repack_U0 : component pfb_multichannel_repack
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => repack_U0_ap_start,
        ap_done => repack_U0_ap_done,
        ap_continue => repack_U0_ap_continue,
        ap_idle => repack_U0_ap_idle,
        ap_ready => repack_U0_ap_ready,
        ch0_out_dout => ch0_out_dout,
        ch0_out_num_data_valid => ch0_out_num_data_valid,
        ch0_out_fifo_cap => ch0_out_fifo_cap,
        ch0_out_empty_n => ch0_out_empty_n,
        ch0_out_read => repack_U0_ch0_out_read,
        ch1_out_dout => ch1_out_dout,
        ch1_out_num_data_valid => ch1_out_num_data_valid,
        ch1_out_fifo_cap => ch1_out_fifo_cap,
        ch1_out_empty_n => ch1_out_empty_n,
        ch1_out_read => repack_U0_ch1_out_read,
        ch2_out_dout => ch2_out_dout,
        ch2_out_num_data_valid => ch2_out_num_data_valid,
        ch2_out_fifo_cap => ch2_out_fifo_cap,
        ch2_out_empty_n => ch2_out_empty_n,
        ch2_out_read => repack_U0_ch2_out_read,
        ch3_out_dout => ch3_out_dout,
        ch3_out_num_data_valid => ch3_out_num_data_valid,
        ch3_out_fifo_cap => ch3_out_fifo_cap,
        ch3_out_empty_n => ch3_out_empty_n,
        ch3_out_read => repack_U0_ch3_out_read,
        stream_fft_to_write_din => repack_U0_stream_fft_to_write_din,
        stream_fft_to_write_num_data_valid => ap_const_lv5_0,
        stream_fft_to_write_fifo_cap => ap_const_lv5_0,
        stream_fft_to_write_full_n => stream_fft_to_write_full_n,
        stream_fft_to_write_write => repack_U0_stream_fft_to_write_write);

    capture_status_U0 : component pfb_multichannel_capture_status
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => capture_status_U0_ap_start,
        ap_done => capture_status_U0_ap_done,
        ap_continue => capture_status_U0_ap_continue,
        ap_idle => capture_status_U0_ap_idle,
        ap_ready => capture_status_U0_ap_ready,
        stat0_s_dout => stat0_s_dout,
        stat0_s_num_data_valid => stat0_s_num_data_valid,
        stat0_s_fifo_cap => stat0_s_fifo_cap,
        stat0_s_empty_n => stat0_s_empty_n,
        stat0_s_read => capture_status_U0_stat0_s_read,
        stat1_s_dout => stat1_s_dout,
        stat1_s_num_data_valid => stat1_s_num_data_valid,
        stat1_s_fifo_cap => stat1_s_fifo_cap,
        stat1_s_empty_n => stat1_s_empty_n,
        stat1_s_read => capture_status_U0_stat1_s_read,
        stat2_s_dout => stat2_s_dout,
        stat2_s_num_data_valid => stat2_s_num_data_valid,
        stat2_s_fifo_cap => stat2_s_fifo_cap,
        stat2_s_empty_n => stat2_s_empty_n,
        stat2_s_read => capture_status_U0_stat2_s_read,
        stat3_s_dout => stat3_s_dout,
        stat3_s_num_data_valid => stat3_s_num_data_valid,
        stat3_s_fifo_cap => stat3_s_fifo_cap,
        stat3_s_empty_n => stat3_s_empty_n,
        stat3_s_read => capture_status_U0_stat3_s_read);

    cfg0_s_U : component pfb_multichannel_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => init_fft_config_U0_cfg0_s_din,
        if_full_n => cfg0_s_full_n,
        if_write => init_fft_config_U0_cfg0_s_write,
        if_dout => cfg0_s_dout,
        if_num_data_valid => cfg0_s_num_data_valid,
        if_fifo_cap => cfg0_s_fifo_cap,
        if_empty_n => cfg0_s_empty_n,
        if_read => fft_config1_1_U0_cfg0_s_read);

    cfg1_s_U : component pfb_multichannel_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => init_fft_config_U0_cfg1_s_din,
        if_full_n => cfg1_s_full_n,
        if_write => init_fft_config_U0_cfg1_s_write,
        if_dout => cfg1_s_dout,
        if_num_data_valid => cfg1_s_num_data_valid,
        if_fifo_cap => cfg1_s_fifo_cap,
        if_empty_n => cfg1_s_empty_n,
        if_read => fft_config1_2_U0_cfg1_s_read);

    cfg2_s_U : component pfb_multichannel_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => init_fft_config_U0_cfg2_s_din,
        if_full_n => cfg2_s_full_n,
        if_write => init_fft_config_U0_cfg2_s_write,
        if_dout => cfg2_s_dout,
        if_num_data_valid => cfg2_s_num_data_valid,
        if_fifo_cap => cfg2_s_fifo_cap,
        if_empty_n => cfg2_s_empty_n,
        if_read => fft_config1_3_U0_cfg2_s_read);

    cfg3_s_U : component pfb_multichannel_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => init_fft_config_U0_cfg3_s_din,
        if_full_n => cfg3_s_full_n,
        if_write => init_fft_config_U0_cfg3_s_write,
        if_dout => cfg3_s_dout,
        if_num_data_valid => cfg3_s_num_data_valid,
        if_fifo_cap => cfg3_s_fifo_cap,
        if_empty_n => cfg3_s_empty_n,
        if_read => fft_config1_U0_cfg3_s_read);

    ch0_in_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => unpack_U0_ch0_in_din,
        if_full_n => ch0_in_full_n,
        if_write => unpack_U0_ch0_in_write,
        if_dout => ch0_in_dout,
        if_num_data_valid => ch0_in_num_data_valid,
        if_fifo_cap => ch0_in_fifo_cap,
        if_empty_n => ch0_in_empty_n,
        if_read => fft_config1_1_U0_ch0_in_read);

    ch1_in_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => unpack_U0_ch1_in_din,
        if_full_n => ch1_in_full_n,
        if_write => unpack_U0_ch1_in_write,
        if_dout => ch1_in_dout,
        if_num_data_valid => ch1_in_num_data_valid,
        if_fifo_cap => ch1_in_fifo_cap,
        if_empty_n => ch1_in_empty_n,
        if_read => fft_config1_2_U0_ch1_in_read);

    ch2_in_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => unpack_U0_ch2_in_din,
        if_full_n => ch2_in_full_n,
        if_write => unpack_U0_ch2_in_write,
        if_dout => ch2_in_dout,
        if_num_data_valid => ch2_in_num_data_valid,
        if_fifo_cap => ch2_in_fifo_cap,
        if_empty_n => ch2_in_empty_n,
        if_read => fft_config1_3_U0_ch2_in_read);

    ch3_in_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => unpack_U0_ch3_in_din,
        if_full_n => ch3_in_full_n,
        if_write => unpack_U0_ch3_in_write,
        if_dout => ch3_in_dout,
        if_num_data_valid => ch3_in_num_data_valid,
        if_fifo_cap => ch3_in_fifo_cap,
        if_empty_n => ch3_in_empty_n,
        if_read => fft_config1_U0_ch3_in_read);

    ch0_out_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_1_U0_ch0_out_din,
        if_full_n => ch0_out_full_n,
        if_write => fft_config1_1_U0_ch0_out_write,
        if_dout => ch0_out_dout,
        if_num_data_valid => ch0_out_num_data_valid,
        if_fifo_cap => ch0_out_fifo_cap,
        if_empty_n => ch0_out_empty_n,
        if_read => repack_U0_ch0_out_read);

    stat0_s_U : component pfb_multichannel_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_1_U0_stat0_s_din,
        if_full_n => stat0_s_full_n,
        if_write => fft_config1_1_U0_stat0_s_write,
        if_dout => stat0_s_dout,
        if_num_data_valid => stat0_s_num_data_valid,
        if_fifo_cap => stat0_s_fifo_cap,
        if_empty_n => stat0_s_empty_n,
        if_read => capture_status_U0_stat0_s_read);

    ch1_out_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_2_U0_ch1_out_din,
        if_full_n => ch1_out_full_n,
        if_write => fft_config1_2_U0_ch1_out_write,
        if_dout => ch1_out_dout,
        if_num_data_valid => ch1_out_num_data_valid,
        if_fifo_cap => ch1_out_fifo_cap,
        if_empty_n => ch1_out_empty_n,
        if_read => repack_U0_ch1_out_read);

    stat1_s_U : component pfb_multichannel_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_2_U0_stat1_s_din,
        if_full_n => stat1_s_full_n,
        if_write => fft_config1_2_U0_stat1_s_write,
        if_dout => stat1_s_dout,
        if_num_data_valid => stat1_s_num_data_valid,
        if_fifo_cap => stat1_s_fifo_cap,
        if_empty_n => stat1_s_empty_n,
        if_read => capture_status_U0_stat1_s_read);

    ch2_out_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_3_U0_ch2_out_din,
        if_full_n => ch2_out_full_n,
        if_write => fft_config1_3_U0_ch2_out_write,
        if_dout => ch2_out_dout,
        if_num_data_valid => ch2_out_num_data_valid,
        if_fifo_cap => ch2_out_fifo_cap,
        if_empty_n => ch2_out_empty_n,
        if_read => repack_U0_ch2_out_read);

    stat2_s_U : component pfb_multichannel_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_3_U0_stat2_s_din,
        if_full_n => stat2_s_full_n,
        if_write => fft_config1_3_U0_stat2_s_write,
        if_dout => stat2_s_dout,
        if_num_data_valid => stat2_s_num_data_valid,
        if_fifo_cap => stat2_s_fifo_cap,
        if_empty_n => stat2_s_empty_n,
        if_read => capture_status_U0_stat2_s_read);

    ch3_out_U : component pfb_multichannel_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_U0_ch3_out_din,
        if_full_n => ch3_out_full_n,
        if_write => fft_config1_U0_ch3_out_write,
        if_dout => ch3_out_dout,
        if_num_data_valid => ch3_out_num_data_valid,
        if_fifo_cap => ch3_out_fifo_cap,
        if_empty_n => ch3_out_empty_n,
        if_read => repack_U0_ch3_out_read);

    stat3_s_U : component pfb_multichannel_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_U0_stat3_s_din,
        if_full_n => stat3_s_full_n,
        if_write => fft_config1_U0_stat3_s_write,
        if_dout => stat3_s_dout,
        if_num_data_valid => stat3_s_num_data_valid,
        if_fifo_cap => stat3_s_fifo_cap,
        if_empty_n => stat3_s_empty_n,
        if_read => capture_status_U0_stat3_s_read);

    start_for_repack_U0_U : component pfb_multichannel_start_for_repack_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_repack_U0_din,
        if_full_n => start_for_repack_U0_full_n,
        if_write => init_fft_config_U0_start_write,
        if_dout => start_for_repack_U0_dout,
        if_empty_n => start_for_repack_U0_empty_n,
        if_read => repack_U0_ap_ready);

    start_for_capture_status_U0_U : component pfb_multichannel_start_for_capture_status_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_capture_status_U0_din,
        if_full_n => start_for_capture_status_U0_full_n,
        if_write => init_fft_config_U0_start_write,
        if_dout => start_for_capture_status_U0_dout,
        if_empty_n => start_for_capture_status_U0_empty_n,
        if_read => capture_status_U0_ap_ready);





    ap_sync_reg_init_fft_config_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_init_fft_config_U0_ap_ready <= ap_const_logic_0;
            else
                if (((real_start and ap_sync_ready) = ap_const_logic_1)) then 
                    ap_sync_reg_init_fft_config_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_init_fft_config_U0_ap_ready <= ap_sync_init_fft_config_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_unpack_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_unpack_U0_ap_ready <= ap_const_logic_0;
            else
                if (((real_start and ap_sync_ready) = ap_const_logic_1)) then 
                    ap_sync_reg_unpack_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_unpack_U0_ap_ready <= ap_sync_unpack_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= ap_sync_done;
    ap_idle <= (unpack_U0_ap_idle and repack_U0_ap_idle and init_fft_config_U0_ap_idle and capture_status_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_done <= (repack_U0_ap_done and capture_status_U0_ap_done);
    ap_sync_init_fft_config_U0_ap_ready <= (init_fft_config_U0_ap_ready or ap_sync_reg_init_fft_config_U0_ap_ready);
    ap_sync_ready <= (ap_sync_unpack_U0_ap_ready and ap_sync_init_fft_config_U0_ap_ready);
    ap_sync_unpack_U0_ap_ready <= (unpack_U0_ap_ready or ap_sync_reg_unpack_U0_ap_ready);
    capture_status_U0_ap_continue <= ap_sync_continue;
    capture_status_U0_ap_start <= start_for_capture_status_U0_empty_n;
    init_fft_config_U0_ap_continue <= ap_const_logic_1;
    init_fft_config_U0_ap_start <= (real_start and (ap_sync_reg_init_fft_config_U0_ap_ready xor ap_const_logic_1));
    init_fft_config_U0_start_full_n <= (start_for_repack_U0_full_n and start_for_capture_status_U0_full_n);
    internal_ap_ready <= ap_sync_ready;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    repack_U0_ap_continue <= ap_sync_continue;
    repack_U0_ap_start <= start_for_repack_U0_empty_n;
    start_for_capture_status_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_repack_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    stream_compute_to_fft_read <= unpack_U0_stream_compute_to_fft_read;
    stream_fft_to_write_din <= repack_U0_stream_fft_to_write_din;
    stream_fft_to_write_write <= repack_U0_stream_fft_to_write_write;
    unpack_U0_ap_continue <= ap_const_logic_1;
    unpack_U0_ap_start <= (real_start and (ap_sync_reg_unpack_U0_ap_ready xor ap_const_logic_1));
end behav;
