-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_read_inputs is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    din_data_i0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i0_TVALID : IN STD_LOGIC;
    din_data_i0_TREADY : OUT STD_LOGIC;
    din_data_q0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q0_TVALID : IN STD_LOGIC;
    din_data_q0_TREADY : OUT STD_LOGIC;
    din_data_i1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i1_TVALID : IN STD_LOGIC;
    din_data_i1_TREADY : OUT STD_LOGIC;
    din_data_q1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q1_TVALID : IN STD_LOGIC;
    din_data_q1_TREADY : OUT STD_LOGIC;
    din_data_i2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i2_TVALID : IN STD_LOGIC;
    din_data_i2_TREADY : OUT STD_LOGIC;
    din_data_q2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q2_TVALID : IN STD_LOGIC;
    din_data_q2_TREADY : OUT STD_LOGIC;
    din_data_i3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i3_TVALID : IN STD_LOGIC;
    din_data_i3_TREADY : OUT STD_LOGIC;
    din_data_q3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q3_TVALID : IN STD_LOGIC;
    din_data_q3_TREADY : OUT STD_LOGIC;
    stream_read_to_compute_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    stream_read_to_compute_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_read_to_compute_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_read_to_compute_full_n : IN STD_LOGIC;
    stream_read_to_compute_write : OUT STD_LOGIC );
end;


architecture behav of pfb_multichannel_read_inputs is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dummy_state_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_read_inputs_Pipeline_read_loop_fu_42_ap_start : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_ap_done : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_ap_idle : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_ap_ready : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY : STD_LOGIC;
    signal grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln15_fu_68_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal regslice_both_din_data_i0_U_apdone_blk : STD_LOGIC;
    signal din_data_i0_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i0_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i0_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q0_U_apdone_blk : STD_LOGIC;
    signal din_data_q0_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q0_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q0_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_i1_U_apdone_blk : STD_LOGIC;
    signal din_data_i1_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i1_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i1_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q1_U_apdone_blk : STD_LOGIC;
    signal din_data_q1_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q1_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q1_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_i2_U_apdone_blk : STD_LOGIC;
    signal din_data_i2_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i2_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i2_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q2_U_apdone_blk : STD_LOGIC;
    signal din_data_q2_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q2_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q2_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_i3_U_apdone_blk : STD_LOGIC;
    signal din_data_i3_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_i3_TVALID_int_regslice : STD_LOGIC;
    signal din_data_i3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_i3_U_ack_in : STD_LOGIC;
    signal regslice_both_din_data_q3_U_apdone_blk : STD_LOGIC;
    signal din_data_q3_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal din_data_q3_TVALID_int_regslice : STD_LOGIC;
    signal din_data_q3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_din_data_q3_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_read_inputs_Pipeline_read_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        din_data_i0_TVALID : IN STD_LOGIC;
        din_data_q0_TVALID : IN STD_LOGIC;
        din_data_i1_TVALID : IN STD_LOGIC;
        din_data_q1_TVALID : IN STD_LOGIC;
        din_data_i2_TVALID : IN STD_LOGIC;
        din_data_q2_TVALID : IN STD_LOGIC;
        din_data_i3_TVALID : IN STD_LOGIC;
        din_data_q3_TVALID : IN STD_LOGIC;
        stream_read_to_compute_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        stream_read_to_compute_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_read_to_compute_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        stream_read_to_compute_full_n : IN STD_LOGIC;
        stream_read_to_compute_write : OUT STD_LOGIC;
        din_data_i0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_i0_TREADY : OUT STD_LOGIC;
        din_data_q0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_q0_TREADY : OUT STD_LOGIC;
        din_data_i1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_i1_TREADY : OUT STD_LOGIC;
        din_data_q1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_q1_TREADY : OUT STD_LOGIC;
        din_data_i2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_i2_TREADY : OUT STD_LOGIC;
        din_data_q2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_q2_TREADY : OUT STD_LOGIC;
        din_data_i3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_i3_TREADY : OUT STD_LOGIC;
        din_data_q3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_data_q3_TREADY : OUT STD_LOGIC );
    end component;


    component pfb_multichannel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_read_inputs_Pipeline_read_loop_fu_42 : component pfb_multichannel_read_inputs_Pipeline_read_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_inputs_Pipeline_read_loop_fu_42_ap_start,
        ap_done => grp_read_inputs_Pipeline_read_loop_fu_42_ap_done,
        ap_idle => grp_read_inputs_Pipeline_read_loop_fu_42_ap_idle,
        ap_ready => grp_read_inputs_Pipeline_read_loop_fu_42_ap_ready,
        din_data_i0_TVALID => din_data_i0_TVALID_int_regslice,
        din_data_q0_TVALID => din_data_q0_TVALID_int_regslice,
        din_data_i1_TVALID => din_data_i1_TVALID_int_regslice,
        din_data_q1_TVALID => din_data_q1_TVALID_int_regslice,
        din_data_i2_TVALID => din_data_i2_TVALID_int_regslice,
        din_data_q2_TVALID => din_data_q2_TVALID_int_regslice,
        din_data_i3_TVALID => din_data_i3_TVALID_int_regslice,
        din_data_q3_TVALID => din_data_q3_TVALID_int_regslice,
        stream_read_to_compute_din => grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_din,
        stream_read_to_compute_num_data_valid => ap_const_lv5_0,
        stream_read_to_compute_fifo_cap => ap_const_lv5_0,
        stream_read_to_compute_full_n => stream_read_to_compute_full_n,
        stream_read_to_compute_write => grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write,
        din_data_i0_TDATA => din_data_i0_TDATA_int_regslice,
        din_data_i0_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY,
        din_data_q0_TDATA => din_data_q0_TDATA_int_regslice,
        din_data_q0_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY,
        din_data_i1_TDATA => din_data_i1_TDATA_int_regslice,
        din_data_i1_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY,
        din_data_q1_TDATA => din_data_q1_TDATA_int_regslice,
        din_data_q1_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY,
        din_data_i2_TDATA => din_data_i2_TDATA_int_regslice,
        din_data_i2_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY,
        din_data_q2_TDATA => din_data_q2_TDATA_int_regslice,
        din_data_q2_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY,
        din_data_i3_TDATA => din_data_i3_TDATA_int_regslice,
        din_data_i3_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY,
        din_data_q3_TDATA => din_data_q3_TDATA_int_regslice,
        din_data_q3_TREADY => grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY);

    regslice_both_din_data_i0_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i0_TDATA,
        vld_in => din_data_i0_TVALID,
        ack_in => regslice_both_din_data_i0_U_ack_in,
        data_out => din_data_i0_TDATA_int_regslice,
        vld_out => din_data_i0_TVALID_int_regslice,
        ack_out => din_data_i0_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i0_U_apdone_blk);

    regslice_both_din_data_q0_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q0_TDATA,
        vld_in => din_data_q0_TVALID,
        ack_in => regslice_both_din_data_q0_U_ack_in,
        data_out => din_data_q0_TDATA_int_regslice,
        vld_out => din_data_q0_TVALID_int_regslice,
        ack_out => din_data_q0_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q0_U_apdone_blk);

    regslice_both_din_data_i1_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i1_TDATA,
        vld_in => din_data_i1_TVALID,
        ack_in => regslice_both_din_data_i1_U_ack_in,
        data_out => din_data_i1_TDATA_int_regslice,
        vld_out => din_data_i1_TVALID_int_regslice,
        ack_out => din_data_i1_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i1_U_apdone_blk);

    regslice_both_din_data_q1_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q1_TDATA,
        vld_in => din_data_q1_TVALID,
        ack_in => regslice_both_din_data_q1_U_ack_in,
        data_out => din_data_q1_TDATA_int_regslice,
        vld_out => din_data_q1_TVALID_int_regslice,
        ack_out => din_data_q1_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q1_U_apdone_blk);

    regslice_both_din_data_i2_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i2_TDATA,
        vld_in => din_data_i2_TVALID,
        ack_in => regslice_both_din_data_i2_U_ack_in,
        data_out => din_data_i2_TDATA_int_regslice,
        vld_out => din_data_i2_TVALID_int_regslice,
        ack_out => din_data_i2_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i2_U_apdone_blk);

    regslice_both_din_data_q2_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q2_TDATA,
        vld_in => din_data_q2_TVALID,
        ack_in => regslice_both_din_data_q2_U_ack_in,
        data_out => din_data_q2_TDATA_int_regslice,
        vld_out => din_data_q2_TVALID_int_regslice,
        ack_out => din_data_q2_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q2_U_apdone_blk);

    regslice_both_din_data_i3_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_i3_TDATA,
        vld_in => din_data_i3_TVALID,
        ack_in => regslice_both_din_data_i3_U_ack_in,
        data_out => din_data_i3_TDATA_int_regslice,
        vld_out => din_data_i3_TVALID_int_regslice,
        ack_out => din_data_i3_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_i3_U_apdone_blk);

    regslice_both_din_data_q3_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => din_data_q3_TDATA,
        vld_in => din_data_q3_TVALID,
        ack_in => regslice_both_din_data_q3_U_ack_in,
        data_out => din_data_q3_TDATA_int_regslice,
        vld_out => din_data_q3_TVALID_int_regslice,
        ack_out => din_data_q3_TREADY_int_regslice,
        apdone_blk => regslice_both_din_data_q3_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_inputs_Pipeline_read_loop_fu_42_ap_ready = ap_const_logic_1)) then 
                    grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                dummy_state_3 <= add_ln15_fu_68_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, grp_read_inputs_Pipeline_read_loop_fu_42_ap_done, ap_CS_fsm_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln15_fu_68_p2 <= std_logic_vector(unsigned(dummy_state_3) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_ap_done)
    begin
        if ((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_read_inputs_Pipeline_read_loop_fu_42_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    din_data_i0_TREADY <= regslice_both_din_data_i0_U_ack_in;

    din_data_i0_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_i0_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY;
        else 
            din_data_i0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_i1_TREADY <= regslice_both_din_data_i1_U_ack_in;

    din_data_i1_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_i1_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY;
        else 
            din_data_i1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_i2_TREADY <= regslice_both_din_data_i2_U_ack_in;

    din_data_i2_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_i2_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY;
        else 
            din_data_i2_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_i3_TREADY <= regslice_both_din_data_i3_U_ack_in;

    din_data_i3_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_i3_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY;
        else 
            din_data_i3_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_q0_TREADY <= regslice_both_din_data_q0_U_ack_in;

    din_data_q0_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_q0_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY;
        else 
            din_data_q0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_q1_TREADY <= regslice_both_din_data_q1_U_ack_in;

    din_data_q1_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_q1_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY;
        else 
            din_data_q1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_q2_TREADY <= regslice_both_din_data_q2_U_ack_in;

    din_data_q2_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_q2_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY;
        else 
            din_data_q2_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    din_data_q3_TREADY <= regslice_both_din_data_q3_U_ack_in;

    din_data_q3_TREADY_int_regslice_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            din_data_q3_TREADY_int_regslice <= grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY;
        else 
            din_data_q3_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    grp_read_inputs_Pipeline_read_loop_fu_42_ap_start <= grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg;
    stream_read_to_compute_din <= grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_din;

    stream_read_to_compute_write_assign_proc : process(grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            stream_read_to_compute_write <= grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write;
        else 
            stream_read_to_compute_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
