-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_fft_config1_s is
port (
    ch3_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ch3_in_empty_n : IN STD_LOGIC;
    ch3_in_read : OUT STD_LOGIC;
    ch3_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    ch3_out_full_n : IN STD_LOGIC;
    ch3_out_write : OUT STD_LOGIC;
    stat3_s_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    stat3_s_full_n : IN STD_LOGIC;
    stat3_s_write : OUT STD_LOGIC;
    cfg3_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    cfg3_s_empty_n : IN STD_LOGIC;
    cfg3_s_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of pfb_multichannel_fft_config1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal fft_syn_config1_6_U0_ap_start : STD_LOGIC;
    signal fft_syn_config1_6_U0_ap_done : STD_LOGIC;
    signal fft_syn_config1_6_U0_ap_idle : STD_LOGIC;
    signal fft_syn_config1_6_U0_ap_ready : STD_LOGIC;
    signal fft_syn_config1_6_U0_ap_continue : STD_LOGIC;
    signal fft_syn_config1_6_U0_xn_read : STD_LOGIC;
    signal fft_syn_config1_6_U0_xk_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_syn_config1_6_U0_xk_write : STD_LOGIC;
    signal fft_syn_config1_6_U0_status_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_syn_config1_6_U0_status_data_V_write : STD_LOGIC;
    signal fft_syn_config1_6_U0_config_ch_data_V_read : STD_LOGIC;

    component pfb_multichannel_fft_syn_config1_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        xn_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xn_empty_n : IN STD_LOGIC;
        xn_read : OUT STD_LOGIC;
        xk_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xk_full_n : IN STD_LOGIC;
        xk_write : OUT STD_LOGIC;
        status_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_data_V_full_n : IN STD_LOGIC;
        status_data_V_write : OUT STD_LOGIC;
        config_ch_data_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        config_ch_data_V_empty_n : IN STD_LOGIC;
        config_ch_data_V_read : OUT STD_LOGIC );
    end component;



begin
    fft_syn_config1_6_U0 : component pfb_multichannel_fft_syn_config1_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ce => ap_const_logic_1,
        ap_start => fft_syn_config1_6_U0_ap_start,
        ap_done => fft_syn_config1_6_U0_ap_done,
        ap_idle => fft_syn_config1_6_U0_ap_idle,
        ap_ready => fft_syn_config1_6_U0_ap_ready,
        ap_continue => fft_syn_config1_6_U0_ap_continue,
        xn_dout => ch3_in_dout,
        xn_empty_n => ch3_in_empty_n,
        xn_read => fft_syn_config1_6_U0_xn_read,
        xk_din => fft_syn_config1_6_U0_xk_din,
        xk_full_n => ch3_out_full_n,
        xk_write => fft_syn_config1_6_U0_xk_write,
        status_data_V_din => fft_syn_config1_6_U0_status_data_V_din,
        status_data_V_full_n => stat3_s_full_n,
        status_data_V_write => fft_syn_config1_6_U0_status_data_V_write,
        config_ch_data_V_dout => cfg3_s_dout,
        config_ch_data_V_empty_n => cfg3_s_empty_n,
        config_ch_data_V_read => fft_syn_config1_6_U0_config_ch_data_V_read);




    ap_ready <= ap_const_logic_1;
    cfg3_s_read <= fft_syn_config1_6_U0_config_ch_data_V_read;
    ch3_in_read <= fft_syn_config1_6_U0_xn_read;
    ch3_out_din <= fft_syn_config1_6_U0_xk_din;
    ch3_out_write <= fft_syn_config1_6_U0_xk_write;
    fft_syn_config1_6_U0_ap_continue <= ap_const_logic_1;
    fft_syn_config1_6_U0_ap_start <= ap_const_logic_1;
    stat3_s_din <= fft_syn_config1_6_U0_status_data_V_din;
    stat3_s_write <= fft_syn_config1_6_U0_status_data_V_write;
end behav;
