-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_read_inputs_Pipeline_read_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    din_data_i0_TVALID : IN STD_LOGIC;
    din_data_q0_TVALID : IN STD_LOGIC;
    din_data_i1_TVALID : IN STD_LOGIC;
    din_data_q1_TVALID : IN STD_LOGIC;
    din_data_i2_TVALID : IN STD_LOGIC;
    din_data_q2_TVALID : IN STD_LOGIC;
    din_data_i3_TVALID : IN STD_LOGIC;
    din_data_q3_TVALID : IN STD_LOGIC;
    stream_read_to_compute_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    stream_read_to_compute_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_read_to_compute_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_read_to_compute_full_n : IN STD_LOGIC;
    stream_read_to_compute_write : OUT STD_LOGIC;
    din_data_i0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i0_TREADY : OUT STD_LOGIC;
    din_data_q0_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q0_TREADY : OUT STD_LOGIC;
    din_data_i1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i1_TREADY : OUT STD_LOGIC;
    din_data_q1_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q1_TREADY : OUT STD_LOGIC;
    din_data_i2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i2_TREADY : OUT STD_LOGIC;
    din_data_q2_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q2_TREADY : OUT STD_LOGIC;
    din_data_i3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_i3_TREADY : OUT STD_LOGIC;
    din_data_q3_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    din_data_q3_TREADY : OUT STD_LOGIC );
end;


architecture behav of pfb_multichannel_read_inputs_Pipeline_read_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln17_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal din_data_i0_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal din_data_q0_TDATA_blk_n : STD_LOGIC;
    signal din_data_i1_TDATA_blk_n : STD_LOGIC;
    signal din_data_q1_TDATA_blk_n : STD_LOGIC;
    signal din_data_i2_TDATA_blk_n : STD_LOGIC;
    signal din_data_q2_TDATA_blk_n : STD_LOGIC;
    signal din_data_i3_TDATA_blk_n : STD_LOGIC;
    signal din_data_q3_TDATA_blk_n : STD_LOGIC;
    signal stream_read_to_compute_blk_n : STD_LOGIC;
    signal pack_i_reg_163 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pack_q_reg_168 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_i_1_reg_173 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_q_1_reg_178 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_i_2_reg_183 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_q_2_reg_188 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_i_3_reg_193 : STD_LOGIC_VECTOR (15 downto 0);
    signal pack_q_3_reg_198 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_fu_56 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal i_8_fu_129_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_7 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pfb_multichannel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    i_fu_56 <= i_8_fu_129_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_56 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                pack_i_1_reg_173 <= din_data_i1_TDATA;
                pack_i_2_reg_183 <= din_data_i2_TDATA;
                pack_i_3_reg_193 <= din_data_i3_TDATA;
                pack_i_reg_163 <= din_data_i0_TDATA;
                pack_q_1_reg_178 <= din_data_q1_TDATA;
                pack_q_2_reg_188 <= din_data_q2_TDATA;
                pack_q_3_reg_198 <= din_data_q3_TDATA;
                pack_q_reg_168 <= din_data_q0_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(din_data_i0_TVALID, icmp_ln17_fu_123_p2, din_data_q0_TVALID, din_data_i1_TVALID, din_data_q1_TVALID, din_data_i2_TVALID, din_data_q2_TVALID, din_data_i3_TVALID, din_data_q3_TVALID)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (((din_data_q3_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((din_data_i3_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((din_data_q2_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((din_data_i2_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((din_data_q1_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((din_data_i1_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((din_data_q0_TVALID = ap_const_logic_0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0)) or ((icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (din_data_i0_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(stream_read_to_compute_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (stream_read_to_compute_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln17_fu_123_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_7 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i_7 <= i_fu_56;
        end if; 
    end process;


    din_data_i0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, din_data_i0_TVALID, icmp_ln17_fu_123_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i0_TDATA_blk_n <= din_data_i0_TVALID;
        else 
            din_data_i0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_i0_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i0_TREADY <= ap_const_logic_1;
        else 
            din_data_i0_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_i1_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i1_TDATA_blk_n <= din_data_i1_TVALID;
        else 
            din_data_i1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_i1_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i1_TREADY <= ap_const_logic_1;
        else 
            din_data_i1_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_i2_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i2_TDATA_blk_n <= din_data_i2_TVALID;
        else 
            din_data_i2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_i2_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i2_TREADY <= ap_const_logic_1;
        else 
            din_data_i2_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_i3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_i3_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i3_TDATA_blk_n <= din_data_i3_TVALID;
        else 
            din_data_i3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_i3_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_i3_TREADY <= ap_const_logic_1;
        else 
            din_data_i3_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_q0_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q0_TDATA_blk_n <= din_data_q0_TVALID;
        else 
            din_data_q0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_q0_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q0_TREADY <= ap_const_logic_1;
        else 
            din_data_q0_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_q1_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q1_TDATA_blk_n <= din_data_q1_TVALID;
        else 
            din_data_q1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_q1_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q1_TREADY <= ap_const_logic_1;
        else 
            din_data_q1_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_q2_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q2_TDATA_blk_n <= din_data_q2_TVALID;
        else 
            din_data_q2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_q2_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q2_TREADY <= ap_const_logic_1;
        else 
            din_data_q2_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    din_data_q3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, din_data_q3_TVALID, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q3_TDATA_blk_n <= din_data_q3_TVALID;
        else 
            din_data_q3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_data_q3_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln17_fu_123_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln17_fu_123_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            din_data_q3_TREADY <= ap_const_logic_1;
        else 
            din_data_q3_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    i_8_fu_129_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_7) + unsigned(ap_const_lv11_1));
    icmp_ln17_fu_123_p2 <= "1" when (ap_sig_allocacmp_i_7 = ap_const_lv11_400) else "0";

    stream_read_to_compute_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_read_to_compute_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_read_to_compute_blk_n <= stream_read_to_compute_full_n;
        else 
            stream_read_to_compute_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_read_to_compute_din <= (((((((pack_q_3_reg_198 & pack_i_3_reg_193) & pack_q_2_reg_188) & pack_i_2_reg_183) & pack_q_1_reg_178) & pack_i_1_reg_173) & pack_q_reg_168) & pack_i_reg_163);

    stream_read_to_compute_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_read_to_compute_write <= ap_const_logic_1;
        else 
            stream_read_to_compute_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
