-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pfb_multichannel_write_outputs is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_fft_to_write_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    stream_fft_to_write_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
    stream_fft_to_write_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
    stream_fft_to_write_empty_n : IN STD_LOGIC;
    stream_fft_to_write_read : OUT STD_LOGIC;
    dout_data_0_TREADY : IN STD_LOGIC;
    dout_data_1_TREADY : IN STD_LOGIC;
    dout_data_2_TREADY : IN STD_LOGIC;
    dout_data_3_TREADY : IN STD_LOGIC;
    dout_data_0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_0_TVALID : OUT STD_LOGIC;
    dout_data_1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_1_TVALID : OUT STD_LOGIC;
    dout_data_2_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_2_TVALID : OUT STD_LOGIC;
    dout_data_3_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dout_data_3_TVALID : OUT STD_LOGIC );
end;


architecture behav of pfb_multichannel_write_outputs is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_dout_data_0_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_data_1_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_data_2_U_apdone_blk : STD_LOGIC;
    signal regslice_both_dout_data_3_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_fft_to_write_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dout_data_0_TDATA_blk_n : STD_LOGIC;
    signal dout_data_1_TDATA_blk_n : STD_LOGIC;
    signal dout_data_2_TDATA_blk_n : STD_LOGIC;
    signal dout_data_3_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_80 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal i_2_fu_132_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal pack_i_fu_143_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_2_fu_147_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_3_fu_157_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_4_fu_167_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_5_fu_177_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_6_fu_187_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_7_fu_197_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_8_fu_207_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal dout_data_0_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal dout_data_0_TVALID_int_regslice : STD_LOGIC;
    signal dout_data_0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_0_U_vld_out : STD_LOGIC;
    signal dout_data_1_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal dout_data_1_TVALID_int_regslice : STD_LOGIC;
    signal dout_data_1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_1_U_vld_out : STD_LOGIC;
    signal dout_data_2_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal dout_data_2_TVALID_int_regslice : STD_LOGIC;
    signal dout_data_2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_2_U_vld_out : STD_LOGIC;
    signal dout_data_3_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal dout_data_3_TVALID_int_regslice : STD_LOGIC;
    signal dout_data_3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_dout_data_3_U_vld_out : STD_LOGIC;
    signal ap_condition_149 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component pfb_multichannel_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component pfb_multichannel_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component pfb_multichannel_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_dout_data_0_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => dout_data_0_TDATA_int_regslice,
        vld_in => dout_data_0_TVALID_int_regslice,
        ack_in => dout_data_0_TREADY_int_regslice,
        data_out => dout_data_0_TDATA,
        vld_out => regslice_both_dout_data_0_U_vld_out,
        ack_out => dout_data_0_TREADY,
        apdone_blk => regslice_both_dout_data_0_U_apdone_blk);

    regslice_both_dout_data_1_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => dout_data_1_TDATA_int_regslice,
        vld_in => dout_data_1_TVALID_int_regslice,
        ack_in => dout_data_1_TREADY_int_regslice,
        data_out => dout_data_1_TDATA,
        vld_out => regslice_both_dout_data_1_U_vld_out,
        ack_out => dout_data_1_TREADY,
        apdone_blk => regslice_both_dout_data_1_U_apdone_blk);

    regslice_both_dout_data_2_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => dout_data_2_TDATA_int_regslice,
        vld_in => dout_data_2_TVALID_int_regslice,
        ack_in => dout_data_2_TREADY_int_regslice,
        data_out => dout_data_2_TDATA,
        vld_out => regslice_both_dout_data_2_U_vld_out,
        ack_out => dout_data_2_TREADY,
        apdone_blk => regslice_both_dout_data_2_U_apdone_blk);

    regslice_both_dout_data_3_U : component pfb_multichannel_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => dout_data_3_TDATA_int_regslice,
        vld_in => dout_data_3_TVALID_int_regslice,
        ack_in => dout_data_3_TREADY_int_regslice,
        data_out => dout_data_3_TDATA,
        vld_out => regslice_both_dout_data_3_U_vld_out,
        ack_out => dout_data_3_TREADY,
        apdone_blk => regslice_both_dout_data_3_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_149)) then
                if ((icmp_ln41_fu_126_p2 = ap_const_lv1_0)) then 
                    i_fu_80 <= i_2_fu_132_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_80 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, regslice_both_dout_data_0_U_apdone_blk, regslice_both_dout_data_1_U_apdone_blk, regslice_both_dout_data_2_U_apdone_blk, regslice_both_dout_data_3_U_apdone_blk, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and ((regslice_both_dout_data_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_0_U_apdone_blk = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, regslice_both_dout_data_0_U_apdone_blk, regslice_both_dout_data_1_U_apdone_blk, regslice_both_dout_data_2_U_apdone_blk, regslice_both_dout_data_3_U_apdone_blk, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and ((regslice_both_dout_data_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_0_U_apdone_blk = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, regslice_both_dout_data_0_U_apdone_blk, regslice_both_dout_data_1_U_apdone_blk, regslice_both_dout_data_2_U_apdone_blk, regslice_both_dout_data_3_U_apdone_blk, ap_block_state2_pp0_stage0_iter1, ap_block_state2_io, ap_block_state3_pp0_stage0_iter2, ap_block_state3_io, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and ((regslice_both_dout_data_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_0_U_apdone_blk = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state2_io) or (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_io_assign_proc : process(dout_data_0_TREADY_int_regslice, dout_data_1_TREADY_int_regslice, dout_data_2_TREADY_int_regslice, dout_data_3_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((dout_data_3_TREADY_int_regslice = ap_const_logic_0) or (dout_data_2_TREADY_int_regslice = ap_const_logic_0) or (dout_data_1_TREADY_int_regslice = ap_const_logic_0) or (dout_data_0_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(stream_fft_to_write_empty_n, regslice_both_dout_data_0_U_apdone_blk, regslice_both_dout_data_1_U_apdone_blk, regslice_both_dout_data_2_U_apdone_blk, regslice_both_dout_data_3_U_apdone_blk, dout_data_0_TREADY_int_regslice, dout_data_1_TREADY_int_regslice, dout_data_2_TREADY_int_regslice, dout_data_3_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_dout_data_3_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_2_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_1_U_apdone_blk = ap_const_logic_1) or (regslice_both_dout_data_0_U_apdone_blk = ap_const_logic_1) or (stream_fft_to_write_empty_n = ap_const_logic_0) or (dout_data_3_TREADY_int_regslice = ap_const_logic_0) or (dout_data_2_TREADY_int_regslice = ap_const_logic_0) or (dout_data_1_TREADY_int_regslice = ap_const_logic_0) or (dout_data_0_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(dout_data_0_TREADY_int_regslice, dout_data_1_TREADY_int_regslice, dout_data_2_TREADY_int_regslice, dout_data_3_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((dout_data_3_TREADY_int_regslice = ap_const_logic_0) or (dout_data_2_TREADY_int_regslice = ap_const_logic_0) or (dout_data_1_TREADY_int_regslice = ap_const_logic_0) or (dout_data_0_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(dout_data_0_TREADY_int_regslice, dout_data_1_TREADY_int_regslice, dout_data_2_TREADY_int_regslice, dout_data_3_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((dout_data_3_TREADY_int_regslice = ap_const_logic_0) or (dout_data_2_TREADY_int_regslice = ap_const_logic_0) or (dout_data_1_TREADY_int_regslice = ap_const_logic_0) or (dout_data_0_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_149_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_149 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_126_p2, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln41_fu_126_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_80, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_80;
        end if; 
    end process;


    dout_data_0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, dout_data_0_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dout_data_0_TDATA_blk_n <= dout_data_0_TREADY_int_regslice;
        else 
            dout_data_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_data_0_TDATA_int_regslice <= (pack_i_fu_143_p1 & trunc_ln44_2_fu_147_p4);
    dout_data_0_TVALID <= regslice_both_dout_data_0_U_vld_out;

    dout_data_0_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dout_data_0_TVALID_int_regslice <= ap_const_logic_1;
        else 
            dout_data_0_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    dout_data_1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, dout_data_1_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dout_data_1_TDATA_blk_n <= dout_data_1_TREADY_int_regslice;
        else 
            dout_data_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_data_1_TDATA_int_regslice <= (trunc_ln44_3_fu_157_p4 & trunc_ln44_4_fu_167_p4);
    dout_data_1_TVALID <= regslice_both_dout_data_1_U_vld_out;

    dout_data_1_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dout_data_1_TVALID_int_regslice <= ap_const_logic_1;
        else 
            dout_data_1_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    dout_data_2_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, dout_data_2_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dout_data_2_TDATA_blk_n <= dout_data_2_TREADY_int_regslice;
        else 
            dout_data_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_data_2_TDATA_int_regslice <= (trunc_ln44_5_fu_177_p4 & trunc_ln44_6_fu_187_p4);
    dout_data_2_TVALID <= regslice_both_dout_data_2_U_vld_out;

    dout_data_2_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dout_data_2_TVALID_int_regslice <= ap_const_logic_1;
        else 
            dout_data_2_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    dout_data_3_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, dout_data_3_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dout_data_3_TDATA_blk_n <= dout_data_3_TREADY_int_regslice;
        else 
            dout_data_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dout_data_3_TDATA_int_regslice <= (trunc_ln44_7_fu_197_p4 & trunc_ln44_8_fu_207_p4);
    dout_data_3_TVALID <= regslice_both_dout_data_3_U_vld_out;

    dout_data_3_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dout_data_3_TVALID_int_regslice <= ap_const_logic_1;
        else 
            dout_data_3_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_132_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv11_1));
    icmp_ln41_fu_126_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv11_400) else "0";
    pack_i_fu_143_p1 <= stream_fft_to_write_dout(16 - 1 downto 0);

    stream_fft_to_write_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_fft_to_write_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_fft_to_write_blk_n <= stream_fft_to_write_empty_n;
        else 
            stream_fft_to_write_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_fft_to_write_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_fft_to_write_read <= ap_const_logic_1;
        else 
            stream_fft_to_write_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_2_fu_147_p4 <= stream_fft_to_write_dout(31 downto 16);
    trunc_ln44_3_fu_157_p4 <= stream_fft_to_write_dout(47 downto 32);
    trunc_ln44_4_fu_167_p4 <= stream_fft_to_write_dout(63 downto 48);
    trunc_ln44_5_fu_177_p4 <= stream_fft_to_write_dout(79 downto 64);
    trunc_ln44_6_fu_187_p4 <= stream_fft_to_write_dout(95 downto 80);
    trunc_ln44_7_fu_197_p4 <= stream_fft_to_write_dout(111 downto 96);
    trunc_ln44_8_fu_207_p4 <= stream_fft_to_write_dout(127 downto 112);
end behav;
