// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_init_fft_config (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        cfg0_s_din,
        cfg0_s_num_data_valid,
        cfg0_s_fifo_cap,
        cfg0_s_full_n,
        cfg0_s_write,
        cfg1_s_din,
        cfg1_s_num_data_valid,
        cfg1_s_fifo_cap,
        cfg1_s_full_n,
        cfg1_s_write,
        cfg2_s_din,
        cfg2_s_num_data_valid,
        cfg2_s_fifo_cap,
        cfg2_s_full_n,
        cfg2_s_write,
        cfg3_s_din,
        cfg3_s_num_data_valid,
        cfg3_s_fifo_cap,
        cfg3_s_full_n,
        cfg3_s_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [15:0] cfg0_s_din;
input  [2:0] cfg0_s_num_data_valid;
input  [2:0] cfg0_s_fifo_cap;
input   cfg0_s_full_n;
output   cfg0_s_write;
output  [15:0] cfg1_s_din;
input  [2:0] cfg1_s_num_data_valid;
input  [2:0] cfg1_s_fifo_cap;
input   cfg1_s_full_n;
output   cfg1_s_write;
output  [15:0] cfg2_s_din;
input  [2:0] cfg2_s_num_data_valid;
input  [2:0] cfg2_s_fifo_cap;
input   cfg2_s_full_n;
output   cfg2_s_write;
output  [15:0] cfg3_s_din;
input  [2:0] cfg3_s_num_data_valid;
input  [2:0] cfg3_s_fifo_cap;
input   cfg3_s_full_n;
output   cfg3_s_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg cfg0_s_write;
reg cfg1_s_write;
reg cfg2_s_write;
reg cfg3_s_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    cfg0_s_blk_n;
reg    cfg1_s_blk_n;
reg    cfg2_s_blk_n;
reg    cfg3_s_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg0_s_blk_n = cfg0_s_full_n;
    end else begin
        cfg0_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg0_s_write = 1'b1;
    end else begin
        cfg0_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg1_s_blk_n = cfg1_s_full_n;
    end else begin
        cfg1_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg1_s_write = 1'b1;
    end else begin
        cfg1_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg2_s_blk_n = cfg2_s_full_n;
    end else begin
        cfg2_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg2_s_write = 1'b1;
    end else begin
        cfg2_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg3_s_blk_n = cfg3_s_full_n;
    end else begin
        cfg3_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        cfg3_s_write = 1'b1;
    end else begin
        cfg3_s_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (cfg3_s_full_n == 1'b0) | (cfg2_s_full_n == 1'b0) | (cfg1_s_full_n == 1'b0) | (cfg0_s_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign cfg0_s_din = 16'd1367;

assign cfg1_s_din = 16'd1367;

assign cfg2_s_din = 16'd1367;

assign cfg3_s_din = 16'd1367;

assign start_out = real_start;

endmodule //pfb_multichannel_init_fft_config
