// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_repack_Pipeline_repack_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ch0_out_dout,
        ch0_out_num_data_valid,
        ch0_out_fifo_cap,
        ch0_out_empty_n,
        ch0_out_read,
        ch1_out_dout,
        ch1_out_num_data_valid,
        ch1_out_fifo_cap,
        ch1_out_empty_n,
        ch1_out_read,
        ch2_out_dout,
        ch2_out_num_data_valid,
        ch2_out_fifo_cap,
        ch2_out_empty_n,
        ch2_out_read,
        ch3_out_dout,
        ch3_out_num_data_valid,
        ch3_out_fifo_cap,
        ch3_out_empty_n,
        ch3_out_read,
        stream_fft_to_write_din,
        stream_fft_to_write_num_data_valid,
        stream_fft_to_write_fifo_cap,
        stream_fft_to_write_full_n,
        stream_fft_to_write_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] ch0_out_dout;
input  [10:0] ch0_out_num_data_valid;
input  [10:0] ch0_out_fifo_cap;
input   ch0_out_empty_n;
output   ch0_out_read;
input  [31:0] ch1_out_dout;
input  [10:0] ch1_out_num_data_valid;
input  [10:0] ch1_out_fifo_cap;
input   ch1_out_empty_n;
output   ch1_out_read;
input  [31:0] ch2_out_dout;
input  [10:0] ch2_out_num_data_valid;
input  [10:0] ch2_out_fifo_cap;
input   ch2_out_empty_n;
output   ch2_out_read;
input  [31:0] ch3_out_dout;
input  [10:0] ch3_out_num_data_valid;
input  [10:0] ch3_out_fifo_cap;
input   ch3_out_empty_n;
output   ch3_out_read;
output  [127:0] stream_fft_to_write_din;
input  [4:0] stream_fft_to_write_num_data_valid;
input  [4:0] stream_fft_to_write_fifo_cap;
input   stream_fft_to_write_full_n;
output   stream_fft_to_write_write;

reg ap_idle;
reg ch0_out_read;
reg ch1_out_read;
reg ch2_out_read;
reg ch3_out_read;
reg stream_fft_to_write_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_105_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ch0_out_blk_n;
wire    ap_block_pp0_stage0;
reg    ch1_out_blk_n;
reg    ch2_out_blk_n;
reg    ch3_out_blk_n;
reg    stream_fft_to_write_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] out_pack_i_fu_204_p3;
reg   [15:0] out_pack_i_reg_498;
wire   [15:0] out_pack_q_fu_244_p3;
reg   [15:0] out_pack_q_reg_503;
wire   [15:0] out_pack_i_1_fu_278_p3;
reg   [15:0] out_pack_i_1_reg_508;
wire   [15:0] out_pack_q_1_fu_318_p3;
reg   [15:0] out_pack_q_1_reg_513;
wire   [15:0] out_pack_i_2_fu_352_p3;
reg   [15:0] out_pack_i_2_reg_518;
wire   [15:0] out_pack_q_2_fu_392_p3;
reg   [15:0] out_pack_q_2_reg_523;
wire   [15:0] out_pack_i_3_fu_426_p3;
reg   [15:0] out_pack_i_3_reg_528;
wire   [15:0] out_pack_q_3_fu_466_p3;
reg   [15:0] out_pack_q_3_reg_533;
reg   [10:0] i_fu_62;
wire   [10:0] i_6_fu_111_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_5;
reg    ap_block_pp0_stage0_01001;
wire   [14:0] trunc_ln118_fu_186_p1;
wire   [0:0] icmp_ln118_fu_190_p2;
wire   [15:0] val0_M_real_fu_122_p1;
wire   [0:0] tmp_fu_178_p3;
wire   [15:0] select_ln118_fu_196_p3;
wire   [14:0] tmp_4_fu_220_p4;
wire   [0:0] icmp_ln118_1_fu_230_p2;
wire   [15:0] val0_M_imag_fu_126_p4;
wire   [0:0] tmp_2_fu_212_p3;
wire   [15:0] select_ln118_1_fu_236_p3;
wire   [14:0] trunc_ln119_fu_260_p1;
wire   [0:0] icmp_ln119_fu_264_p2;
wire   [15:0] val1_M_real_fu_136_p1;
wire   [0:0] tmp_3_fu_252_p3;
wire   [15:0] select_ln119_fu_270_p3;
wire   [14:0] tmp_6_fu_294_p4;
wire   [0:0] icmp_ln119_1_fu_304_p2;
wire   [15:0] val1_M_imag_fu_140_p4;
wire   [0:0] tmp_5_fu_286_p3;
wire   [15:0] select_ln119_1_fu_310_p3;
wire   [14:0] trunc_ln120_fu_334_p1;
wire   [0:0] icmp_ln120_fu_338_p2;
wire   [15:0] val2_M_real_fu_150_p1;
wire   [0:0] tmp_7_fu_326_p3;
wire   [15:0] select_ln120_fu_344_p3;
wire   [14:0] tmp_8_fu_368_p4;
wire   [0:0] icmp_ln120_1_fu_378_p2;
wire   [15:0] val2_M_imag_fu_154_p4;
wire   [0:0] tmp_9_fu_360_p3;
wire   [15:0] select_ln120_1_fu_384_p3;
wire   [14:0] trunc_ln121_fu_408_p1;
wire   [0:0] icmp_ln121_fu_412_p2;
wire   [15:0] val3_M_real_fu_164_p1;
wire   [0:0] tmp_10_fu_400_p3;
wire   [15:0] select_ln121_fu_418_p3;
wire   [14:0] tmp_1_fu_442_p4;
wire   [0:0] icmp_ln121_1_fu_452_p2;
wire   [15:0] val3_M_imag_fu_168_p4;
wire   [0:0] tmp_11_fu_434_p3;
wire   [15:0] select_ln121_1_fu_458_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_62 = 11'd0;
#0 ap_done_reg = 1'b0;
end

pfb_multichannel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_105_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_62 <= i_6_fu_111_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_62 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        out_pack_i_1_reg_508 <= out_pack_i_1_fu_278_p3;
        out_pack_i_2_reg_518 <= out_pack_i_2_fu_352_p3;
        out_pack_i_3_reg_528 <= out_pack_i_3_fu_426_p3;
        out_pack_i_reg_498 <= out_pack_i_fu_204_p3;
        out_pack_q_1_reg_513 <= out_pack_q_1_fu_318_p3;
        out_pack_q_2_reg_523 <= out_pack_q_2_fu_392_p3;
        out_pack_q_3_reg_533 <= out_pack_q_3_fu_466_p3;
        out_pack_q_reg_503 <= out_pack_q_fu_244_p3;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_105_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_5 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch0_out_blk_n = ch0_out_empty_n;
    end else begin
        ch0_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch0_out_read = 1'b1;
    end else begin
        ch0_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch1_out_blk_n = ch1_out_empty_n;
    end else begin
        ch1_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch1_out_read = 1'b1;
    end else begin
        ch1_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch2_out_blk_n = ch2_out_empty_n;
    end else begin
        ch2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch2_out_read = 1'b1;
    end else begin
        ch2_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch3_out_blk_n = ch3_out_empty_n;
    end else begin
        ch3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ch3_out_read = 1'b1;
    end else begin
        ch3_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        stream_fft_to_write_blk_n = stream_fft_to_write_full_n;
    end else begin
        stream_fft_to_write_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        stream_fft_to_write_write = 1'b1;
    end else begin
        stream_fft_to_write_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ch3_out_empty_n == 1'b0) | (ch2_out_empty_n == 1'b0) | (ch1_out_empty_n == 1'b0) | (ch0_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (stream_fft_to_write_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_6_fu_111_p2 = (ap_sig_allocacmp_i_5 + 11'd1);

assign icmp_ln109_fu_105_p2 = ((ap_sig_allocacmp_i_5 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln118_1_fu_230_p2 = ((tmp_4_fu_220_p4 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_190_p2 = ((trunc_ln118_fu_186_p1 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_1_fu_304_p2 = ((tmp_6_fu_294_p4 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_264_p2 = ((trunc_ln119_fu_260_p1 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln120_1_fu_378_p2 = ((tmp_8_fu_368_p4 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_338_p2 = ((trunc_ln120_fu_334_p1 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln121_1_fu_452_p2 = ((tmp_1_fu_442_p4 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_412_p2 = ((trunc_ln121_fu_408_p1 == 15'd0) ? 1'b1 : 1'b0);

assign out_pack_i_1_fu_278_p3 = ((tmp_3_fu_252_p3[0:0] == 1'b1) ? select_ln119_fu_270_p3 : val1_M_real_fu_136_p1);

assign out_pack_i_2_fu_352_p3 = ((tmp_7_fu_326_p3[0:0] == 1'b1) ? select_ln120_fu_344_p3 : val2_M_real_fu_150_p1);

assign out_pack_i_3_fu_426_p3 = ((tmp_10_fu_400_p3[0:0] == 1'b1) ? select_ln121_fu_418_p3 : val3_M_real_fu_164_p1);

assign out_pack_i_fu_204_p3 = ((tmp_fu_178_p3[0:0] == 1'b1) ? select_ln118_fu_196_p3 : val0_M_real_fu_122_p1);

assign out_pack_q_1_fu_318_p3 = ((tmp_5_fu_286_p3[0:0] == 1'b1) ? select_ln119_1_fu_310_p3 : val1_M_imag_fu_140_p4);

assign out_pack_q_2_fu_392_p3 = ((tmp_9_fu_360_p3[0:0] == 1'b1) ? select_ln120_1_fu_384_p3 : val2_M_imag_fu_154_p4);

assign out_pack_q_3_fu_466_p3 = ((tmp_11_fu_434_p3[0:0] == 1'b1) ? select_ln121_1_fu_458_p3 : val3_M_imag_fu_168_p4);

assign out_pack_q_fu_244_p3 = ((tmp_2_fu_212_p3[0:0] == 1'b1) ? select_ln118_1_fu_236_p3 : val0_M_imag_fu_126_p4);

assign select_ln118_1_fu_236_p3 = ((icmp_ln118_1_fu_230_p2[0:0] == 1'b1) ? 16'd32769 : val0_M_imag_fu_126_p4);

assign select_ln118_fu_196_p3 = ((icmp_ln118_fu_190_p2[0:0] == 1'b1) ? 16'd32769 : val0_M_real_fu_122_p1);

assign select_ln119_1_fu_310_p3 = ((icmp_ln119_1_fu_304_p2[0:0] == 1'b1) ? 16'd32769 : val1_M_imag_fu_140_p4);

assign select_ln119_fu_270_p3 = ((icmp_ln119_fu_264_p2[0:0] == 1'b1) ? 16'd32769 : val1_M_real_fu_136_p1);

assign select_ln120_1_fu_384_p3 = ((icmp_ln120_1_fu_378_p2[0:0] == 1'b1) ? 16'd32769 : val2_M_imag_fu_154_p4);

assign select_ln120_fu_344_p3 = ((icmp_ln120_fu_338_p2[0:0] == 1'b1) ? 16'd32769 : val2_M_real_fu_150_p1);

assign select_ln121_1_fu_458_p3 = ((icmp_ln121_1_fu_452_p2[0:0] == 1'b1) ? 16'd32769 : val3_M_imag_fu_168_p4);

assign select_ln121_fu_418_p3 = ((icmp_ln121_fu_412_p2[0:0] == 1'b1) ? 16'd32769 : val3_M_real_fu_164_p1);

assign stream_fft_to_write_din = {{{{{{{{out_pack_q_3_reg_533}, {out_pack_i_3_reg_528}}, {out_pack_q_2_reg_523}}, {out_pack_i_2_reg_518}}, {out_pack_q_1_reg_513}}, {out_pack_i_1_reg_508}}, {out_pack_q_reg_503}}, {out_pack_i_reg_498}};

assign tmp_10_fu_400_p3 = ch3_out_dout[32'd15];

assign tmp_11_fu_434_p3 = ch3_out_dout[32'd31];

assign tmp_1_fu_442_p4 = {{ch3_out_dout[30:16]}};

assign tmp_2_fu_212_p3 = ch0_out_dout[32'd31];

assign tmp_3_fu_252_p3 = ch1_out_dout[32'd15];

assign tmp_4_fu_220_p4 = {{ch0_out_dout[30:16]}};

assign tmp_5_fu_286_p3 = ch1_out_dout[32'd31];

assign tmp_6_fu_294_p4 = {{ch1_out_dout[30:16]}};

assign tmp_7_fu_326_p3 = ch2_out_dout[32'd15];

assign tmp_8_fu_368_p4 = {{ch2_out_dout[30:16]}};

assign tmp_9_fu_360_p3 = ch2_out_dout[32'd31];

assign tmp_fu_178_p3 = ch0_out_dout[32'd15];

assign trunc_ln118_fu_186_p1 = ch0_out_dout[14:0];

assign trunc_ln119_fu_260_p1 = ch1_out_dout[14:0];

assign trunc_ln120_fu_334_p1 = ch2_out_dout[14:0];

assign trunc_ln121_fu_408_p1 = ch3_out_dout[14:0];

assign val0_M_imag_fu_126_p4 = {{ch0_out_dout[31:16]}};

assign val0_M_real_fu_122_p1 = ch0_out_dout[15:0];

assign val1_M_imag_fu_140_p4 = {{ch1_out_dout[31:16]}};

assign val1_M_real_fu_136_p1 = ch1_out_dout[15:0];

assign val2_M_imag_fu_154_p4 = {{ch2_out_dout[31:16]}};

assign val2_M_real_fu_150_p1 = ch2_out_dout[15:0];

assign val3_M_imag_fu_168_p4 = {{ch3_out_dout[31:16]}};

assign val3_M_real_fu_164_p1 = ch3_out_dout[15:0];

endmodule //pfb_multichannel_repack_Pipeline_repack_loop
