// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_unpack (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_compute_to_fft_dout,
        stream_compute_to_fft_num_data_valid,
        stream_compute_to_fft_fifo_cap,
        stream_compute_to_fft_empty_n,
        stream_compute_to_fft_read,
        ch0_in_din,
        ch0_in_num_data_valid,
        ch0_in_fifo_cap,
        ch0_in_full_n,
        ch0_in_write,
        ch1_in_din,
        ch1_in_num_data_valid,
        ch1_in_fifo_cap,
        ch1_in_full_n,
        ch1_in_write,
        ch2_in_din,
        ch2_in_num_data_valid,
        ch2_in_fifo_cap,
        ch2_in_full_n,
        ch2_in_write,
        ch3_in_din,
        ch3_in_num_data_valid,
        ch3_in_fifo_cap,
        ch3_in_full_n,
        ch3_in_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] stream_compute_to_fft_dout;
input  [4:0] stream_compute_to_fft_num_data_valid;
input  [4:0] stream_compute_to_fft_fifo_cap;
input   stream_compute_to_fft_empty_n;
output   stream_compute_to_fft_read;
output  [31:0] ch0_in_din;
input  [10:0] ch0_in_num_data_valid;
input  [10:0] ch0_in_fifo_cap;
input   ch0_in_full_n;
output   ch0_in_write;
output  [31:0] ch1_in_din;
input  [10:0] ch1_in_num_data_valid;
input  [10:0] ch1_in_fifo_cap;
input   ch1_in_full_n;
output   ch1_in_write;
output  [31:0] ch2_in_din;
input  [10:0] ch2_in_num_data_valid;
input  [10:0] ch2_in_fifo_cap;
input   ch2_in_full_n;
output   ch2_in_write;
output  [31:0] ch3_in_din;
input  [10:0] ch3_in_num_data_valid;
input  [10:0] ch3_in_fifo_cap;
input   ch3_in_full_n;
output   ch3_in_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_compute_to_fft_read;
reg ch0_in_write;
reg ch1_in_write;
reg ch2_in_write;
reg ch3_in_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] dummy_state_1;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ap_start;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ap_done;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ap_idle;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ap_ready;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_stream_compute_to_fft_read;
wire   [31:0] grp_unpack_Pipeline_unpack_loop_fu_30_ch0_in_din;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ch0_in_write;
wire   [31:0] grp_unpack_Pipeline_unpack_loop_fu_30_ch1_in_din;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ch1_in_write;
wire   [31:0] grp_unpack_Pipeline_unpack_loop_fu_30_ch2_in_din;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ch2_in_write;
wire   [31:0] grp_unpack_Pipeline_unpack_loop_fu_30_ch3_in_din;
wire    grp_unpack_Pipeline_unpack_loop_fu_30_ch3_in_write;
reg    grp_unpack_Pipeline_unpack_loop_fu_30_ap_start_reg;
reg    ap_block_state1_ignore_call10;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln82_fu_48_p2;
reg    ap_block_state1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 dummy_state_1 = 32'd0;
#0 grp_unpack_Pipeline_unpack_loop_fu_30_ap_start_reg = 1'b0;
end

pfb_multichannel_unpack_Pipeline_unpack_loop grp_unpack_Pipeline_unpack_loop_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_unpack_Pipeline_unpack_loop_fu_30_ap_start),
    .ap_done(grp_unpack_Pipeline_unpack_loop_fu_30_ap_done),
    .ap_idle(grp_unpack_Pipeline_unpack_loop_fu_30_ap_idle),
    .ap_ready(grp_unpack_Pipeline_unpack_loop_fu_30_ap_ready),
    .stream_compute_to_fft_dout(stream_compute_to_fft_dout),
    .stream_compute_to_fft_num_data_valid(5'd0),
    .stream_compute_to_fft_fifo_cap(5'd0),
    .stream_compute_to_fft_empty_n(stream_compute_to_fft_empty_n),
    .stream_compute_to_fft_read(grp_unpack_Pipeline_unpack_loop_fu_30_stream_compute_to_fft_read),
    .ch0_in_din(grp_unpack_Pipeline_unpack_loop_fu_30_ch0_in_din),
    .ch0_in_num_data_valid(11'd0),
    .ch0_in_fifo_cap(11'd0),
    .ch0_in_full_n(ch0_in_full_n),
    .ch0_in_write(grp_unpack_Pipeline_unpack_loop_fu_30_ch0_in_write),
    .ch1_in_din(grp_unpack_Pipeline_unpack_loop_fu_30_ch1_in_din),
    .ch1_in_num_data_valid(11'd0),
    .ch1_in_fifo_cap(11'd0),
    .ch1_in_full_n(ch1_in_full_n),
    .ch1_in_write(grp_unpack_Pipeline_unpack_loop_fu_30_ch1_in_write),
    .ch2_in_din(grp_unpack_Pipeline_unpack_loop_fu_30_ch2_in_din),
    .ch2_in_num_data_valid(11'd0),
    .ch2_in_fifo_cap(11'd0),
    .ch2_in_full_n(ch2_in_full_n),
    .ch2_in_write(grp_unpack_Pipeline_unpack_loop_fu_30_ch2_in_write),
    .ch3_in_din(grp_unpack_Pipeline_unpack_loop_fu_30_ch3_in_din),
    .ch3_in_num_data_valid(11'd0),
    .ch3_in_fifo_cap(11'd0),
    .ch3_in_full_n(ch3_in_full_n),
    .ch3_in_write(grp_unpack_Pipeline_unpack_loop_fu_30_ch3_in_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_unpack_Pipeline_unpack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_unpack_Pipeline_unpack_loop_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call10) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_unpack_Pipeline_unpack_loop_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_unpack_Pipeline_unpack_loop_fu_30_ap_ready == 1'b1)) begin
            grp_unpack_Pipeline_unpack_loop_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dummy_state_1 <= add_ln82_fu_48_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_unpack_Pipeline_unpack_loop_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_unpack_Pipeline_unpack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_unpack_Pipeline_unpack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch0_in_write = grp_unpack_Pipeline_unpack_loop_fu_30_ch0_in_write;
    end else begin
        ch0_in_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch1_in_write = grp_unpack_Pipeline_unpack_loop_fu_30_ch1_in_write;
    end else begin
        ch1_in_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch2_in_write = grp_unpack_Pipeline_unpack_loop_fu_30_ch2_in_write;
    end else begin
        ch2_in_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch3_in_write = grp_unpack_Pipeline_unpack_loop_fu_30_ch3_in_write;
    end else begin
        ch3_in_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        stream_compute_to_fft_read = grp_unpack_Pipeline_unpack_loop_fu_30_stream_compute_to_fft_read;
    end else begin
        stream_compute_to_fft_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_unpack_Pipeline_unpack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln82_fu_48_p2 = (dummy_state_1 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ch0_in_din = grp_unpack_Pipeline_unpack_loop_fu_30_ch0_in_din;

assign ch1_in_din = grp_unpack_Pipeline_unpack_loop_fu_30_ch1_in_din;

assign ch2_in_din = grp_unpack_Pipeline_unpack_loop_fu_30_ch2_in_din;

assign ch3_in_din = grp_unpack_Pipeline_unpack_loop_fu_30_ch3_in_din;

assign grp_unpack_Pipeline_unpack_loop_fu_30_ap_start = grp_unpack_Pipeline_unpack_loop_fu_30_ap_start_reg;

endmodule //pfb_multichannel_unpack
