// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_write_outputs (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_fft_to_write_dout,
        stream_fft_to_write_num_data_valid,
        stream_fft_to_write_fifo_cap,
        stream_fft_to_write_empty_n,
        stream_fft_to_write_read,
        dout_data_0_TDATA,
        dout_data_0_TVALID,
        dout_data_0_TREADY,
        dout_data_1_TDATA,
        dout_data_1_TVALID,
        dout_data_1_TREADY,
        dout_data_2_TDATA,
        dout_data_2_TVALID,
        dout_data_2_TREADY,
        dout_data_3_TDATA,
        dout_data_3_TVALID,
        dout_data_3_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] stream_fft_to_write_dout;
input  [4:0] stream_fft_to_write_num_data_valid;
input  [4:0] stream_fft_to_write_fifo_cap;
input   stream_fft_to_write_empty_n;
output   stream_fft_to_write_read;
output  [31:0] dout_data_0_TDATA;
output   dout_data_0_TVALID;
input   dout_data_0_TREADY;
output  [31:0] dout_data_1_TDATA;
output   dout_data_1_TVALID;
input   dout_data_1_TREADY;
output  [31:0] dout_data_2_TDATA;
output   dout_data_2_TVALID;
input   dout_data_2_TREADY;
output  [31:0] dout_data_3_TDATA;
output   dout_data_3_TVALID;
input   dout_data_3_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_fft_to_write_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] dummy_state;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_ap_start;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_ap_done;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_ap_idle;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_ap_ready;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TREADY;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TREADY;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TREADY;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TREADY;
wire   [31:0] grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TDATA;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TVALID;
wire   [31:0] grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TDATA;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TVALID;
wire   [31:0] grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TDATA;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TVALID;
wire   [31:0] grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TDATA;
wire    grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TVALID;
reg    grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg;
reg    ap_block_state1_ignore_call10;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln45_fu_52_p2;
reg    ap_block_state1;
wire    ap_CS_fsm_state3;
wire    regslice_both_dout_data_0_U_apdone_blk;
wire    regslice_both_dout_data_1_U_apdone_blk;
wire    regslice_both_dout_data_2_U_apdone_blk;
wire    regslice_both_dout_data_3_U_apdone_blk;
reg    ap_block_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    dout_data_0_TREADY_int_regslice;
wire    regslice_both_dout_data_0_U_vld_out;
wire    dout_data_1_TREADY_int_regslice;
wire    regslice_both_dout_data_1_U_vld_out;
wire    dout_data_2_TREADY_int_regslice;
wire    regslice_both_dout_data_2_U_vld_out;
wire    dout_data_3_TREADY_int_regslice;
wire    regslice_both_dout_data_3_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 dummy_state = 32'd0;
#0 grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg = 1'b0;
end

pfb_multichannel_write_outputs_Pipeline_write_loop grp_write_outputs_Pipeline_write_loop_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_outputs_Pipeline_write_loop_fu_34_ap_start),
    .ap_done(grp_write_outputs_Pipeline_write_loop_fu_34_ap_done),
    .ap_idle(grp_write_outputs_Pipeline_write_loop_fu_34_ap_idle),
    .ap_ready(grp_write_outputs_Pipeline_write_loop_fu_34_ap_ready),
    .stream_fft_to_write_dout(stream_fft_to_write_dout),
    .stream_fft_to_write_num_data_valid(5'd0),
    .stream_fft_to_write_fifo_cap(5'd0),
    .stream_fft_to_write_empty_n(stream_fft_to_write_empty_n),
    .stream_fft_to_write_read(grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read),
    .dout_data_0_TREADY(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TREADY),
    .dout_data_1_TREADY(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TREADY),
    .dout_data_2_TREADY(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TREADY),
    .dout_data_3_TREADY(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TREADY),
    .dout_data_0_TDATA(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TDATA),
    .dout_data_0_TVALID(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TVALID),
    .dout_data_1_TDATA(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TDATA),
    .dout_data_1_TVALID(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TVALID),
    .dout_data_2_TDATA(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TDATA),
    .dout_data_2_TVALID(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TVALID),
    .dout_data_3_TDATA(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TDATA),
    .dout_data_3_TVALID(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TVALID)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dout_data_0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TDATA),
    .vld_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TVALID),
    .ack_in(dout_data_0_TREADY_int_regslice),
    .data_out(dout_data_0_TDATA),
    .vld_out(regslice_both_dout_data_0_U_vld_out),
    .ack_out(dout_data_0_TREADY),
    .apdone_blk(regslice_both_dout_data_0_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dout_data_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TDATA),
    .vld_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TVALID),
    .ack_in(dout_data_1_TREADY_int_regslice),
    .data_out(dout_data_1_TDATA),
    .vld_out(regslice_both_dout_data_1_U_vld_out),
    .ack_out(dout_data_1_TREADY),
    .apdone_blk(regslice_both_dout_data_1_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dout_data_2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TDATA),
    .vld_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TVALID),
    .ack_in(dout_data_2_TREADY_int_regslice),
    .data_out(dout_data_2_TDATA),
    .vld_out(regslice_both_dout_data_2_U_vld_out),
    .ack_out(dout_data_2_TREADY),
    .apdone_blk(regslice_both_dout_data_2_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_dout_data_3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TDATA),
    .vld_in(grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TVALID),
    .ack_in(dout_data_3_TREADY_int_regslice),
    .data_out(dout_data_3_TDATA),
    .vld_out(regslice_both_dout_data_3_U_vld_out),
    .ack_out(dout_data_3_TREADY),
    .apdone_blk(regslice_both_dout_data_3_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call10) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_write_outputs_Pipeline_write_loop_fu_34_ap_ready == 1'b1)) begin
            grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dummy_state <= add_ln45_fu_52_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_write_outputs_Pipeline_write_loop_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        stream_fft_to_write_read = grp_write_outputs_Pipeline_write_loop_fu_34_stream_fft_to_write_read;
    end else begin
        stream_fft_to_write_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_write_outputs_Pipeline_write_loop_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln45_fu_52_p2 = (dummy_state + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3 = ((regslice_both_dout_data_3_U_apdone_blk == 1'b1) | (regslice_both_dout_data_2_U_apdone_blk == 1'b1) | (regslice_both_dout_data_1_U_apdone_blk == 1'b1) | (regslice_both_dout_data_0_U_apdone_blk == 1'b1));
end

assign dout_data_0_TVALID = regslice_both_dout_data_0_U_vld_out;

assign dout_data_1_TVALID = regslice_both_dout_data_1_U_vld_out;

assign dout_data_2_TVALID = regslice_both_dout_data_2_U_vld_out;

assign dout_data_3_TVALID = regslice_both_dout_data_3_U_vld_out;

assign grp_write_outputs_Pipeline_write_loop_fu_34_ap_start = grp_write_outputs_Pipeline_write_loop_fu_34_ap_start_reg;

assign grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_0_TREADY = (dout_data_0_TREADY_int_regslice & ap_CS_fsm_state2);

assign grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_1_TREADY = (dout_data_1_TREADY_int_regslice & ap_CS_fsm_state2);

assign grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_2_TREADY = (dout_data_2_TREADY_int_regslice & ap_CS_fsm_state2);

assign grp_write_outputs_Pipeline_write_loop_fu_34_dout_data_3_TREADY = (dout_data_3_TREADY_int_regslice & ap_CS_fsm_state2);

endmodule //pfb_multichannel_write_outputs
