// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_read_inputs (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        din_data_i0_TVALID,
        din_data_q0_TVALID,
        din_data_i1_TVALID,
        din_data_q1_TVALID,
        din_data_i2_TVALID,
        din_data_q2_TVALID,
        din_data_i3_TVALID,
        din_data_q3_TVALID,
        stream_read_to_compute_din,
        stream_read_to_compute_num_data_valid,
        stream_read_to_compute_fifo_cap,
        stream_read_to_compute_full_n,
        stream_read_to_compute_write,
        din_data_i0_TDATA,
        din_data_i0_TREADY,
        din_data_q0_TDATA,
        din_data_q0_TREADY,
        din_data_i1_TDATA,
        din_data_i1_TREADY,
        din_data_q1_TDATA,
        din_data_q1_TREADY,
        din_data_i2_TDATA,
        din_data_i2_TREADY,
        din_data_q2_TDATA,
        din_data_q2_TREADY,
        din_data_i3_TDATA,
        din_data_i3_TREADY,
        din_data_q3_TDATA,
        din_data_q3_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   din_data_i0_TVALID;
input   din_data_q0_TVALID;
input   din_data_i1_TVALID;
input   din_data_q1_TVALID;
input   din_data_i2_TVALID;
input   din_data_q2_TVALID;
input   din_data_i3_TVALID;
input   din_data_q3_TVALID;
output  [127:0] stream_read_to_compute_din;
input  [12:0] stream_read_to_compute_num_data_valid;
input  [12:0] stream_read_to_compute_fifo_cap;
input   stream_read_to_compute_full_n;
output   stream_read_to_compute_write;
input  [15:0] din_data_i0_TDATA;
output   din_data_i0_TREADY;
input  [15:0] din_data_q0_TDATA;
output   din_data_q0_TREADY;
input  [15:0] din_data_i1_TDATA;
output   din_data_i1_TREADY;
input  [15:0] din_data_q1_TDATA;
output   din_data_q1_TREADY;
input  [15:0] din_data_i2_TDATA;
output   din_data_i2_TREADY;
input  [15:0] din_data_q2_TDATA;
output   din_data_q2_TREADY;
input  [15:0] din_data_i3_TDATA;
output   din_data_i3_TREADY;
input  [15:0] din_data_q3_TDATA;
output   din_data_q3_TREADY;

reg ap_idle;
reg stream_read_to_compute_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln12_fu_123_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    din_data_i0_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    din_data_q0_TDATA_blk_n;
reg    din_data_i1_TDATA_blk_n;
reg    din_data_q1_TDATA_blk_n;
reg    din_data_i2_TDATA_blk_n;
reg    din_data_q2_TDATA_blk_n;
reg    din_data_i3_TDATA_blk_n;
reg    din_data_q3_TDATA_blk_n;
reg    stream_read_to_compute_blk_n;
reg   [15:0] pack_i_reg_163;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] pack_q_reg_168;
reg   [15:0] pack_i_1_reg_173;
reg   [15:0] pack_q_1_reg_178;
reg   [15:0] pack_i_2_reg_183;
reg   [15:0] pack_q_2_reg_188;
reg   [15:0] pack_i_3_reg_193;
reg   [15:0] pack_q_3_reg_198;
reg   [10:0] i_fu_56;
wire   [10:0] i_8_fu_129_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_7;
reg    ap_block_pp0_stage0_01001;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    regslice_both_din_data_i0_U_apdone_blk;
wire   [15:0] din_data_i0_TDATA_int_regslice;
wire    din_data_i0_TVALID_int_regslice;
reg    din_data_i0_TREADY_int_regslice;
wire    regslice_both_din_data_i0_U_ack_in;
wire    regslice_both_din_data_q0_U_apdone_blk;
wire   [15:0] din_data_q0_TDATA_int_regslice;
wire    din_data_q0_TVALID_int_regslice;
reg    din_data_q0_TREADY_int_regslice;
wire    regslice_both_din_data_q0_U_ack_in;
wire    regslice_both_din_data_i1_U_apdone_blk;
wire   [15:0] din_data_i1_TDATA_int_regslice;
wire    din_data_i1_TVALID_int_regslice;
reg    din_data_i1_TREADY_int_regslice;
wire    regslice_both_din_data_i1_U_ack_in;
wire    regslice_both_din_data_q1_U_apdone_blk;
wire   [15:0] din_data_q1_TDATA_int_regslice;
wire    din_data_q1_TVALID_int_regslice;
reg    din_data_q1_TREADY_int_regslice;
wire    regslice_both_din_data_q1_U_ack_in;
wire    regslice_both_din_data_i2_U_apdone_blk;
wire   [15:0] din_data_i2_TDATA_int_regslice;
wire    din_data_i2_TVALID_int_regslice;
reg    din_data_i2_TREADY_int_regslice;
wire    regslice_both_din_data_i2_U_ack_in;
wire    regslice_both_din_data_q2_U_apdone_blk;
wire   [15:0] din_data_q2_TDATA_int_regslice;
wire    din_data_q2_TVALID_int_regslice;
reg    din_data_q2_TREADY_int_regslice;
wire    regslice_both_din_data_q2_U_ack_in;
wire    regslice_both_din_data_i3_U_apdone_blk;
wire   [15:0] din_data_i3_TDATA_int_regslice;
wire    din_data_i3_TVALID_int_regslice;
reg    din_data_i3_TREADY_int_regslice;
wire    regslice_both_din_data_i3_U_ack_in;
wire    regslice_both_din_data_q3_U_apdone_blk;
wire   [15:0] din_data_q3_TDATA_int_regslice;
wire    din_data_q3_TVALID_int_regslice;
reg    din_data_q3_TREADY_int_regslice;
wire    regslice_both_din_data_q3_U_ack_in;
reg    ap_condition_159;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_56 = 11'd0;
end

pfb_multichannel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i0_TDATA),
    .vld_in(din_data_i0_TVALID),
    .ack_in(regslice_both_din_data_i0_U_ack_in),
    .data_out(din_data_i0_TDATA_int_regslice),
    .vld_out(din_data_i0_TVALID_int_regslice),
    .ack_out(din_data_i0_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i0_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q0_TDATA),
    .vld_in(din_data_q0_TVALID),
    .ack_in(regslice_both_din_data_q0_U_ack_in),
    .data_out(din_data_q0_TDATA_int_regslice),
    .vld_out(din_data_q0_TVALID_int_regslice),
    .ack_out(din_data_q0_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q0_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i1_TDATA),
    .vld_in(din_data_i1_TVALID),
    .ack_in(regslice_both_din_data_i1_U_ack_in),
    .data_out(din_data_i1_TDATA_int_regslice),
    .vld_out(din_data_i1_TVALID_int_regslice),
    .ack_out(din_data_i1_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i1_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q1_TDATA),
    .vld_in(din_data_q1_TVALID),
    .ack_in(regslice_both_din_data_q1_U_ack_in),
    .data_out(din_data_q1_TDATA_int_regslice),
    .vld_out(din_data_q1_TVALID_int_regslice),
    .ack_out(din_data_q1_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q1_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i2_TDATA),
    .vld_in(din_data_i2_TVALID),
    .ack_in(regslice_both_din_data_i2_U_ack_in),
    .data_out(din_data_i2_TDATA_int_regslice),
    .vld_out(din_data_i2_TVALID_int_regslice),
    .ack_out(din_data_i2_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i2_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q2_TDATA),
    .vld_in(din_data_q2_TVALID),
    .ack_in(regslice_both_din_data_q2_U_ack_in),
    .data_out(din_data_q2_TDATA_int_regslice),
    .vld_out(din_data_q2_TVALID_int_regslice),
    .ack_out(din_data_q2_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q2_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i3_TDATA),
    .vld_in(din_data_i3_TVALID),
    .ack_in(regslice_both_din_data_i3_U_ack_in),
    .data_out(din_data_i3_TDATA_int_regslice),
    .vld_out(din_data_i3_TVALID_int_regslice),
    .ack_out(din_data_i3_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i3_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q3_TDATA),
    .vld_in(din_data_q3_TVALID),
    .ack_in(regslice_both_din_data_q3_U_ack_in),
    .data_out(din_data_q3_TDATA_int_regslice),
    .vld_out(din_data_q3_TVALID_int_regslice),
    .ack_out(din_data_q3_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q3_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_159)) begin
        if ((icmp_ln12_fu_123_p2 == 1'd0)) begin
            i_fu_56 <= i_8_fu_129_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pack_i_1_reg_173 <= din_data_i1_TDATA_int_regslice;
        pack_i_2_reg_183 <= din_data_i2_TDATA_int_regslice;
        pack_i_3_reg_193 <= din_data_i3_TDATA_int_regslice;
        pack_i_reg_163 <= din_data_i0_TDATA_int_regslice;
        pack_q_1_reg_178 <= din_data_q1_TDATA_int_regslice;
        pack_q_2_reg_188 <= din_data_q2_TDATA_int_regslice;
        pack_q_3_reg_198 <= din_data_q3_TDATA_int_regslice;
        pack_q_reg_168 <= din_data_q0_TDATA_int_regslice;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln12_fu_123_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_7 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_7 = i_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i0_TDATA_blk_n = din_data_i0_TVALID_int_regslice;
    end else begin
        din_data_i0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i0_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i1_TDATA_blk_n = din_data_i1_TVALID_int_regslice;
    end else begin
        din_data_i1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i1_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i2_TDATA_blk_n = din_data_i2_TVALID_int_regslice;
    end else begin
        din_data_i2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i2_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i3_TDATA_blk_n = din_data_i3_TVALID_int_regslice;
    end else begin
        din_data_i3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_i3_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_i3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q0_TDATA_blk_n = din_data_q0_TVALID_int_regslice;
    end else begin
        din_data_q0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q0_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q1_TDATA_blk_n = din_data_q1_TVALID_int_regslice;
    end else begin
        din_data_q1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q1_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q2_TDATA_blk_n = din_data_q2_TVALID_int_regslice;
    end else begin
        din_data_q2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q2_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q3_TDATA_blk_n = din_data_q3_TVALID_int_regslice;
    end else begin
        din_data_q3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_fu_123_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_data_q3_TREADY_int_regslice = 1'b1;
    end else begin
        din_data_q3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_read_to_compute_blk_n = stream_read_to_compute_full_n;
    end else begin
        stream_read_to_compute_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_read_to_compute_write = 1'b1;
    end else begin
        stream_read_to_compute_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_q3_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_i3_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_q2_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_i2_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_q1_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_i1_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_q0_TVALID_int_regslice == 1'b0)) | ((icmp_ln12_fu_123_p2 == 1'd0) & (din_data_i0_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (stream_read_to_compute_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_159 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign din_data_i0_TREADY = regslice_both_din_data_i0_U_ack_in;

assign din_data_i1_TREADY = regslice_both_din_data_i1_U_ack_in;

assign din_data_i2_TREADY = regslice_both_din_data_i2_U_ack_in;

assign din_data_i3_TREADY = regslice_both_din_data_i3_U_ack_in;

assign din_data_q0_TREADY = regslice_both_din_data_q0_U_ack_in;

assign din_data_q1_TREADY = regslice_both_din_data_q1_U_ack_in;

assign din_data_q2_TREADY = regslice_both_din_data_q2_U_ack_in;

assign din_data_q3_TREADY = regslice_both_din_data_q3_U_ack_in;

assign i_8_fu_129_p2 = (ap_sig_allocacmp_i_7 + 11'd1);

assign icmp_ln12_fu_123_p2 = ((ap_sig_allocacmp_i_7 == 11'd1024) ? 1'b1 : 1'b0);

assign stream_read_to_compute_din = {{{{{{{{pack_q_3_reg_198}, {pack_i_3_reg_193}}, {pack_q_2_reg_188}}, {pack_i_2_reg_183}}, {pack_q_1_reg_178}}, {pack_i_1_reg_173}}, {pack_q_reg_168}}, {pack_i_reg_163}};

endmodule //pfb_multichannel_read_inputs
