// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_fft_config1_2 (
        ch1_in_dout,
        ch1_in_empty_n,
        ch1_in_read,
        ch1_out_din,
        ch1_out_full_n,
        ch1_out_write,
        stat1_s_din,
        stat1_s_full_n,
        stat1_s_write,
        cfg1_s_dout,
        cfg1_s_empty_n,
        cfg1_s_read,
        ap_clk,
        ap_rst,
        ap_ready
);


input  [31:0] ch1_in_dout;
input   ch1_in_empty_n;
output   ch1_in_read;
output  [31:0] ch1_out_din;
input   ch1_out_full_n;
output   ch1_out_write;
output  [7:0] stat1_s_din;
input   stat1_s_full_n;
output   stat1_s_write;
input  [15:0] cfg1_s_dout;
input   cfg1_s_empty_n;
output   cfg1_s_read;
input   ap_clk;
input   ap_rst;
output   ap_ready;

wire    fft_syn_config1_4_U0_ap_start;
wire    fft_syn_config1_4_U0_ap_done;
wire    fft_syn_config1_4_U0_ap_idle;
wire    fft_syn_config1_4_U0_ap_ready;
wire    fft_syn_config1_4_U0_ap_continue;
wire    fft_syn_config1_4_U0_xn_read;
wire   [31:0] fft_syn_config1_4_U0_xk_din;
wire    fft_syn_config1_4_U0_xk_write;
wire   [7:0] fft_syn_config1_4_U0_status_data_V_din;
wire    fft_syn_config1_4_U0_status_data_V_write;
wire    fft_syn_config1_4_U0_config_ch_data_V_read;

pfb_multichannel_fft_syn_config1_4 fft_syn_config1_4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(1'b1),
    .ap_start(fft_syn_config1_4_U0_ap_start),
    .ap_done(fft_syn_config1_4_U0_ap_done),
    .ap_idle(fft_syn_config1_4_U0_ap_idle),
    .ap_ready(fft_syn_config1_4_U0_ap_ready),
    .ap_continue(fft_syn_config1_4_U0_ap_continue),
    .xn_dout(ch1_in_dout),
    .xn_empty_n(ch1_in_empty_n),
    .xn_read(fft_syn_config1_4_U0_xn_read),
    .xk_din(fft_syn_config1_4_U0_xk_din),
    .xk_full_n(ch1_out_full_n),
    .xk_write(fft_syn_config1_4_U0_xk_write),
    .status_data_V_din(fft_syn_config1_4_U0_status_data_V_din),
    .status_data_V_full_n(stat1_s_full_n),
    .status_data_V_write(fft_syn_config1_4_U0_status_data_V_write),
    .config_ch_data_V_dout(cfg1_s_dout),
    .config_ch_data_V_empty_n(cfg1_s_empty_n),
    .config_ch_data_V_read(fft_syn_config1_4_U0_config_ch_data_V_read)
);

assign ap_ready = 1'b1;

assign cfg1_s_read = fft_syn_config1_4_U0_config_ch_data_V_read;

assign ch1_in_read = fft_syn_config1_4_U0_xn_read;

assign ch1_out_din = fft_syn_config1_4_U0_xk_din;

assign ch1_out_write = fft_syn_config1_4_U0_xk_write;

assign fft_syn_config1_4_U0_ap_continue = 1'b1;

assign fft_syn_config1_4_U0_ap_start = 1'b1;

assign stat1_s_din = fft_syn_config1_4_U0_status_data_V_din;

assign stat1_s_write = fft_syn_config1_4_U0_status_data_V_write;

endmodule //pfb_multichannel_fft_config1_2
