// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_fft (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        stream_compute_to_fft_dout,
        stream_compute_to_fft_empty_n,
        stream_compute_to_fft_read,
        stream_fft_to_write_din,
        stream_fft_to_write_full_n,
        stream_fft_to_write_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [127:0] stream_compute_to_fft_dout;
input   stream_compute_to_fft_empty_n;
output   stream_compute_to_fft_read;
output  [127:0] stream_fft_to_write_din;
input   stream_fft_to_write_full_n;
output   stream_fft_to_write_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    unpack_U0_ap_start;
wire    unpack_U0_start_full_n;
wire    unpack_U0_ap_done;
wire    unpack_U0_ap_continue;
wire    unpack_U0_ap_idle;
wire    unpack_U0_ap_ready;
wire    unpack_U0_stream_compute_to_fft_read;
wire   [31:0] unpack_U0_ch0_in_din;
wire    unpack_U0_ch0_in_write;
wire   [31:0] unpack_U0_ch1_in_din;
wire    unpack_U0_ch1_in_write;
wire   [31:0] unpack_U0_ch2_in_din;
wire    unpack_U0_ch2_in_write;
wire   [31:0] unpack_U0_ch3_in_din;
wire    unpack_U0_ch3_in_write;
wire    unpack_U0_start_out;
wire    unpack_U0_start_write;
wire    fft_Block_entry13_proc1_U0_ap_start;
wire    fft_Block_entry13_proc1_U0_ap_done;
wire    fft_Block_entry13_proc1_U0_ap_continue;
wire    fft_Block_entry13_proc1_U0_ap_idle;
wire    fft_Block_entry13_proc1_U0_ap_ready;
wire   [15:0] fft_Block_entry13_proc1_U0_cfg0_s_din;
wire    fft_Block_entry13_proc1_U0_cfg0_s_write;
wire   [15:0] fft_Block_entry13_proc1_U0_cfg1_s_din;
wire    fft_Block_entry13_proc1_U0_cfg1_s_write;
wire   [15:0] fft_Block_entry13_proc1_U0_cfg2_s_din;
wire    fft_Block_entry13_proc1_U0_cfg2_s_write;
wire   [15:0] fft_Block_entry13_proc1_U0_cfg3_s_din;
wire    fft_Block_entry13_proc1_U0_cfg3_s_write;
wire    fft_config1_1_U0_ch0_in_read;
wire   [31:0] fft_config1_1_U0_ch0_out_din;
wire    fft_config1_1_U0_ch0_out_write;
wire   [7:0] fft_config1_1_U0_stat0_s_din;
wire    fft_config1_1_U0_stat0_s_write;
wire    fft_config1_1_U0_cfg0_s_read;
wire    fft_config1_1_U0_ap_ready;
wire    fft_config1_2_U0_ch1_in_read;
wire   [31:0] fft_config1_2_U0_ch1_out_din;
wire    fft_config1_2_U0_ch1_out_write;
wire   [7:0] fft_config1_2_U0_stat1_s_din;
wire    fft_config1_2_U0_stat1_s_write;
wire    fft_config1_2_U0_cfg1_s_read;
wire    fft_config1_2_U0_ap_ready;
wire    fft_config1_3_U0_ch2_in_read;
wire   [31:0] fft_config1_3_U0_ch2_out_din;
wire    fft_config1_3_U0_ch2_out_write;
wire   [7:0] fft_config1_3_U0_stat2_s_din;
wire    fft_config1_3_U0_stat2_s_write;
wire    fft_config1_3_U0_cfg2_s_read;
wire    fft_config1_3_U0_ap_ready;
wire    fft_config1_U0_ch3_in_read;
wire   [31:0] fft_config1_U0_ch3_out_din;
wire    fft_config1_U0_ch3_out_write;
wire   [7:0] fft_config1_U0_stat3_s_din;
wire    fft_config1_U0_stat3_s_write;
wire    fft_config1_U0_cfg3_s_read;
wire    fft_config1_U0_ap_ready;
wire    repack_U0_ap_start;
wire    repack_U0_ap_done;
wire    repack_U0_ap_continue;
wire    repack_U0_ap_idle;
wire    repack_U0_ap_ready;
wire    repack_U0_ch0_out_read;
wire    repack_U0_ch1_out_read;
wire    repack_U0_ch2_out_read;
wire    repack_U0_ch3_out_read;
wire   [127:0] repack_U0_stream_fft_to_write_din;
wire    repack_U0_stream_fft_to_write_write;
wire    ap_sync_continue;
wire    fft_Block_entry19_proc2_U0_ap_start;
wire    fft_Block_entry19_proc2_U0_ap_done;
wire    fft_Block_entry19_proc2_U0_ap_continue;
wire    fft_Block_entry19_proc2_U0_ap_idle;
wire    fft_Block_entry19_proc2_U0_ap_ready;
wire    fft_Block_entry19_proc2_U0_stat0_s_read;
wire    fft_Block_entry19_proc2_U0_stat1_s_read;
wire    fft_Block_entry19_proc2_U0_stat2_s_read;
wire    fft_Block_entry19_proc2_U0_stat3_s_read;
wire    ch0_in_full_n;
wire   [31:0] ch0_in_dout;
wire   [2:0] ch0_in_num_data_valid;
wire   [2:0] ch0_in_fifo_cap;
wire    ch0_in_empty_n;
wire    ch1_in_full_n;
wire   [31:0] ch1_in_dout;
wire   [2:0] ch1_in_num_data_valid;
wire   [2:0] ch1_in_fifo_cap;
wire    ch1_in_empty_n;
wire    ch2_in_full_n;
wire   [31:0] ch2_in_dout;
wire   [2:0] ch2_in_num_data_valid;
wire   [2:0] ch2_in_fifo_cap;
wire    ch2_in_empty_n;
wire    ch3_in_full_n;
wire   [31:0] ch3_in_dout;
wire   [2:0] ch3_in_num_data_valid;
wire   [2:0] ch3_in_fifo_cap;
wire    ch3_in_empty_n;
wire    cfg0_s_full_n;
wire   [15:0] cfg0_s_dout;
wire   [2:0] cfg0_s_num_data_valid;
wire   [2:0] cfg0_s_fifo_cap;
wire    cfg0_s_empty_n;
wire    cfg1_s_full_n;
wire   [15:0] cfg1_s_dout;
wire   [2:0] cfg1_s_num_data_valid;
wire   [2:0] cfg1_s_fifo_cap;
wire    cfg1_s_empty_n;
wire    cfg2_s_full_n;
wire   [15:0] cfg2_s_dout;
wire   [2:0] cfg2_s_num_data_valid;
wire   [2:0] cfg2_s_fifo_cap;
wire    cfg2_s_empty_n;
wire    cfg3_s_full_n;
wire   [15:0] cfg3_s_dout;
wire   [2:0] cfg3_s_num_data_valid;
wire   [2:0] cfg3_s_fifo_cap;
wire    cfg3_s_empty_n;
wire    ch0_out_full_n;
wire   [31:0] ch0_out_dout;
wire   [2:0] ch0_out_num_data_valid;
wire   [2:0] ch0_out_fifo_cap;
wire    ch0_out_empty_n;
wire    stat0_s_full_n;
wire   [7:0] stat0_s_dout;
wire   [2:0] stat0_s_num_data_valid;
wire   [2:0] stat0_s_fifo_cap;
wire    stat0_s_empty_n;
wire    ch1_out_full_n;
wire   [31:0] ch1_out_dout;
wire   [2:0] ch1_out_num_data_valid;
wire   [2:0] ch1_out_fifo_cap;
wire    ch1_out_empty_n;
wire    stat1_s_full_n;
wire   [7:0] stat1_s_dout;
wire   [2:0] stat1_s_num_data_valid;
wire   [2:0] stat1_s_fifo_cap;
wire    stat1_s_empty_n;
wire    ch2_out_full_n;
wire   [31:0] ch2_out_dout;
wire   [2:0] ch2_out_num_data_valid;
wire   [2:0] ch2_out_fifo_cap;
wire    ch2_out_empty_n;
wire    stat2_s_full_n;
wire   [7:0] stat2_s_dout;
wire   [2:0] stat2_s_num_data_valid;
wire   [2:0] stat2_s_fifo_cap;
wire    stat2_s_empty_n;
wire    ch3_out_full_n;
wire   [31:0] ch3_out_dout;
wire   [2:0] ch3_out_num_data_valid;
wire   [2:0] ch3_out_fifo_cap;
wire    ch3_out_empty_n;
wire    stat3_s_full_n;
wire   [7:0] stat3_s_dout;
wire   [2:0] stat3_s_num_data_valid;
wire   [2:0] stat3_s_fifo_cap;
wire    stat3_s_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_unpack_U0_ap_ready;
wire    ap_sync_unpack_U0_ap_ready;
reg    ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready;
wire    ap_sync_fft_Block_entry13_proc1_U0_ap_ready;
wire   [0:0] start_for_repack_U0_din;
wire    start_for_repack_U0_full_n;
wire   [0:0] start_for_repack_U0_dout;
wire    start_for_repack_U0_empty_n;
wire   [0:0] start_for_fft_Block_entry19_proc2_U0_din;
wire    start_for_fft_Block_entry19_proc2_U0_full_n;
wire   [0:0] start_for_fft_Block_entry19_proc2_U0_dout;
wire    start_for_fft_Block_entry19_proc2_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_sync_reg_unpack_U0_ap_ready = 1'b0;
#0 ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready = 1'b0;
end

pfb_multichannel_unpack unpack_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(unpack_U0_ap_start),
    .start_full_n(unpack_U0_start_full_n),
    .ap_done(unpack_U0_ap_done),
    .ap_continue(unpack_U0_ap_continue),
    .ap_idle(unpack_U0_ap_idle),
    .ap_ready(unpack_U0_ap_ready),
    .stream_compute_to_fft_dout(stream_compute_to_fft_dout),
    .stream_compute_to_fft_num_data_valid(13'd0),
    .stream_compute_to_fft_fifo_cap(13'd0),
    .stream_compute_to_fft_empty_n(stream_compute_to_fft_empty_n),
    .stream_compute_to_fft_read(unpack_U0_stream_compute_to_fft_read),
    .ch0_in_din(unpack_U0_ch0_in_din),
    .ch0_in_num_data_valid(ch0_in_num_data_valid),
    .ch0_in_fifo_cap(ch0_in_fifo_cap),
    .ch0_in_full_n(ch0_in_full_n),
    .ch0_in_write(unpack_U0_ch0_in_write),
    .ch1_in_din(unpack_U0_ch1_in_din),
    .ch1_in_num_data_valid(ch1_in_num_data_valid),
    .ch1_in_fifo_cap(ch1_in_fifo_cap),
    .ch1_in_full_n(ch1_in_full_n),
    .ch1_in_write(unpack_U0_ch1_in_write),
    .ch2_in_din(unpack_U0_ch2_in_din),
    .ch2_in_num_data_valid(ch2_in_num_data_valid),
    .ch2_in_fifo_cap(ch2_in_fifo_cap),
    .ch2_in_full_n(ch2_in_full_n),
    .ch2_in_write(unpack_U0_ch2_in_write),
    .ch3_in_din(unpack_U0_ch3_in_din),
    .ch3_in_num_data_valid(ch3_in_num_data_valid),
    .ch3_in_fifo_cap(ch3_in_fifo_cap),
    .ch3_in_full_n(ch3_in_full_n),
    .ch3_in_write(unpack_U0_ch3_in_write),
    .start_out(unpack_U0_start_out),
    .start_write(unpack_U0_start_write)
);

pfb_multichannel_fft_Block_entry13_proc1 fft_Block_entry13_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_Block_entry13_proc1_U0_ap_start),
    .ap_done(fft_Block_entry13_proc1_U0_ap_done),
    .ap_continue(fft_Block_entry13_proc1_U0_ap_continue),
    .ap_idle(fft_Block_entry13_proc1_U0_ap_idle),
    .ap_ready(fft_Block_entry13_proc1_U0_ap_ready),
    .cfg0_s_din(fft_Block_entry13_proc1_U0_cfg0_s_din),
    .cfg0_s_num_data_valid(cfg0_s_num_data_valid),
    .cfg0_s_fifo_cap(cfg0_s_fifo_cap),
    .cfg0_s_full_n(cfg0_s_full_n),
    .cfg0_s_write(fft_Block_entry13_proc1_U0_cfg0_s_write),
    .cfg1_s_din(fft_Block_entry13_proc1_U0_cfg1_s_din),
    .cfg1_s_num_data_valid(cfg1_s_num_data_valid),
    .cfg1_s_fifo_cap(cfg1_s_fifo_cap),
    .cfg1_s_full_n(cfg1_s_full_n),
    .cfg1_s_write(fft_Block_entry13_proc1_U0_cfg1_s_write),
    .cfg2_s_din(fft_Block_entry13_proc1_U0_cfg2_s_din),
    .cfg2_s_num_data_valid(cfg2_s_num_data_valid),
    .cfg2_s_fifo_cap(cfg2_s_fifo_cap),
    .cfg2_s_full_n(cfg2_s_full_n),
    .cfg2_s_write(fft_Block_entry13_proc1_U0_cfg2_s_write),
    .cfg3_s_din(fft_Block_entry13_proc1_U0_cfg3_s_din),
    .cfg3_s_num_data_valid(cfg3_s_num_data_valid),
    .cfg3_s_fifo_cap(cfg3_s_fifo_cap),
    .cfg3_s_full_n(cfg3_s_full_n),
    .cfg3_s_write(fft_Block_entry13_proc1_U0_cfg3_s_write)
);

pfb_multichannel_fft_config1_1 fft_config1_1_U0(
    .ch0_in_dout(ch0_in_dout),
    .ch0_in_empty_n(ch0_in_empty_n),
    .ch0_in_read(fft_config1_1_U0_ch0_in_read),
    .ch0_out_din(fft_config1_1_U0_ch0_out_din),
    .ch0_out_full_n(ch0_out_full_n),
    .ch0_out_write(fft_config1_1_U0_ch0_out_write),
    .stat0_s_din(fft_config1_1_U0_stat0_s_din),
    .stat0_s_full_n(stat0_s_full_n),
    .stat0_s_write(fft_config1_1_U0_stat0_s_write),
    .cfg0_s_dout(cfg0_s_dout),
    .cfg0_s_empty_n(cfg0_s_empty_n),
    .cfg0_s_read(fft_config1_1_U0_cfg0_s_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ready(fft_config1_1_U0_ap_ready)
);

pfb_multichannel_fft_config1_2 fft_config1_2_U0(
    .ch1_in_dout(ch1_in_dout),
    .ch1_in_empty_n(ch1_in_empty_n),
    .ch1_in_read(fft_config1_2_U0_ch1_in_read),
    .ch1_out_din(fft_config1_2_U0_ch1_out_din),
    .ch1_out_full_n(ch1_out_full_n),
    .ch1_out_write(fft_config1_2_U0_ch1_out_write),
    .stat1_s_din(fft_config1_2_U0_stat1_s_din),
    .stat1_s_full_n(stat1_s_full_n),
    .stat1_s_write(fft_config1_2_U0_stat1_s_write),
    .cfg1_s_dout(cfg1_s_dout),
    .cfg1_s_empty_n(cfg1_s_empty_n),
    .cfg1_s_read(fft_config1_2_U0_cfg1_s_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ready(fft_config1_2_U0_ap_ready)
);

pfb_multichannel_fft_config1_3 fft_config1_3_U0(
    .ch2_in_dout(ch2_in_dout),
    .ch2_in_empty_n(ch2_in_empty_n),
    .ch2_in_read(fft_config1_3_U0_ch2_in_read),
    .ch2_out_din(fft_config1_3_U0_ch2_out_din),
    .ch2_out_full_n(ch2_out_full_n),
    .ch2_out_write(fft_config1_3_U0_ch2_out_write),
    .stat2_s_din(fft_config1_3_U0_stat2_s_din),
    .stat2_s_full_n(stat2_s_full_n),
    .stat2_s_write(fft_config1_3_U0_stat2_s_write),
    .cfg2_s_dout(cfg2_s_dout),
    .cfg2_s_empty_n(cfg2_s_empty_n),
    .cfg2_s_read(fft_config1_3_U0_cfg2_s_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ready(fft_config1_3_U0_ap_ready)
);

pfb_multichannel_fft_config1_s fft_config1_U0(
    .ch3_in_dout(ch3_in_dout),
    .ch3_in_empty_n(ch3_in_empty_n),
    .ch3_in_read(fft_config1_U0_ch3_in_read),
    .ch3_out_din(fft_config1_U0_ch3_out_din),
    .ch3_out_full_n(ch3_out_full_n),
    .ch3_out_write(fft_config1_U0_ch3_out_write),
    .stat3_s_din(fft_config1_U0_stat3_s_din),
    .stat3_s_full_n(stat3_s_full_n),
    .stat3_s_write(fft_config1_U0_stat3_s_write),
    .cfg3_s_dout(cfg3_s_dout),
    .cfg3_s_empty_n(cfg3_s_empty_n),
    .cfg3_s_read(fft_config1_U0_cfg3_s_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ready(fft_config1_U0_ap_ready)
);

pfb_multichannel_repack repack_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(repack_U0_ap_start),
    .ap_done(repack_U0_ap_done),
    .ap_continue(repack_U0_ap_continue),
    .ap_idle(repack_U0_ap_idle),
    .ap_ready(repack_U0_ap_ready),
    .ch0_out_dout(ch0_out_dout),
    .ch0_out_num_data_valid(ch0_out_num_data_valid),
    .ch0_out_fifo_cap(ch0_out_fifo_cap),
    .ch0_out_empty_n(ch0_out_empty_n),
    .ch0_out_read(repack_U0_ch0_out_read),
    .ch1_out_dout(ch1_out_dout),
    .ch1_out_num_data_valid(ch1_out_num_data_valid),
    .ch1_out_fifo_cap(ch1_out_fifo_cap),
    .ch1_out_empty_n(ch1_out_empty_n),
    .ch1_out_read(repack_U0_ch1_out_read),
    .ch2_out_dout(ch2_out_dout),
    .ch2_out_num_data_valid(ch2_out_num_data_valid),
    .ch2_out_fifo_cap(ch2_out_fifo_cap),
    .ch2_out_empty_n(ch2_out_empty_n),
    .ch2_out_read(repack_U0_ch2_out_read),
    .ch3_out_dout(ch3_out_dout),
    .ch3_out_num_data_valid(ch3_out_num_data_valid),
    .ch3_out_fifo_cap(ch3_out_fifo_cap),
    .ch3_out_empty_n(ch3_out_empty_n),
    .ch3_out_read(repack_U0_ch3_out_read),
    .stream_fft_to_write_din(repack_U0_stream_fft_to_write_din),
    .stream_fft_to_write_num_data_valid(13'd0),
    .stream_fft_to_write_fifo_cap(13'd0),
    .stream_fft_to_write_full_n(stream_fft_to_write_full_n),
    .stream_fft_to_write_write(repack_U0_stream_fft_to_write_write)
);

pfb_multichannel_fft_Block_entry19_proc2 fft_Block_entry19_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_Block_entry19_proc2_U0_ap_start),
    .ap_done(fft_Block_entry19_proc2_U0_ap_done),
    .ap_continue(fft_Block_entry19_proc2_U0_ap_continue),
    .ap_idle(fft_Block_entry19_proc2_U0_ap_idle),
    .ap_ready(fft_Block_entry19_proc2_U0_ap_ready),
    .stat0_s_dout(stat0_s_dout),
    .stat0_s_num_data_valid(stat0_s_num_data_valid),
    .stat0_s_fifo_cap(stat0_s_fifo_cap),
    .stat0_s_empty_n(stat0_s_empty_n),
    .stat0_s_read(fft_Block_entry19_proc2_U0_stat0_s_read),
    .stat1_s_dout(stat1_s_dout),
    .stat1_s_num_data_valid(stat1_s_num_data_valid),
    .stat1_s_fifo_cap(stat1_s_fifo_cap),
    .stat1_s_empty_n(stat1_s_empty_n),
    .stat1_s_read(fft_Block_entry19_proc2_U0_stat1_s_read),
    .stat2_s_dout(stat2_s_dout),
    .stat2_s_num_data_valid(stat2_s_num_data_valid),
    .stat2_s_fifo_cap(stat2_s_fifo_cap),
    .stat2_s_empty_n(stat2_s_empty_n),
    .stat2_s_read(fft_Block_entry19_proc2_U0_stat2_s_read),
    .stat3_s_dout(stat3_s_dout),
    .stat3_s_num_data_valid(stat3_s_num_data_valid),
    .stat3_s_fifo_cap(stat3_s_fifo_cap),
    .stat3_s_empty_n(stat3_s_empty_n),
    .stat3_s_read(fft_Block_entry19_proc2_U0_stat3_s_read)
);

pfb_multichannel_fifo_w32_d2_S ch0_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(unpack_U0_ch0_in_din),
    .if_full_n(ch0_in_full_n),
    .if_write(unpack_U0_ch0_in_write),
    .if_dout(ch0_in_dout),
    .if_num_data_valid(ch0_in_num_data_valid),
    .if_fifo_cap(ch0_in_fifo_cap),
    .if_empty_n(ch0_in_empty_n),
    .if_read(fft_config1_1_U0_ch0_in_read)
);

pfb_multichannel_fifo_w32_d2_S ch1_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(unpack_U0_ch1_in_din),
    .if_full_n(ch1_in_full_n),
    .if_write(unpack_U0_ch1_in_write),
    .if_dout(ch1_in_dout),
    .if_num_data_valid(ch1_in_num_data_valid),
    .if_fifo_cap(ch1_in_fifo_cap),
    .if_empty_n(ch1_in_empty_n),
    .if_read(fft_config1_2_U0_ch1_in_read)
);

pfb_multichannel_fifo_w32_d2_S ch2_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(unpack_U0_ch2_in_din),
    .if_full_n(ch2_in_full_n),
    .if_write(unpack_U0_ch2_in_write),
    .if_dout(ch2_in_dout),
    .if_num_data_valid(ch2_in_num_data_valid),
    .if_fifo_cap(ch2_in_fifo_cap),
    .if_empty_n(ch2_in_empty_n),
    .if_read(fft_config1_3_U0_ch2_in_read)
);

pfb_multichannel_fifo_w32_d2_S ch3_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(unpack_U0_ch3_in_din),
    .if_full_n(ch3_in_full_n),
    .if_write(unpack_U0_ch3_in_write),
    .if_dout(ch3_in_dout),
    .if_num_data_valid(ch3_in_num_data_valid),
    .if_fifo_cap(ch3_in_fifo_cap),
    .if_empty_n(ch3_in_empty_n),
    .if_read(fft_config1_U0_ch3_in_read)
);

pfb_multichannel_fifo_w16_d2_S cfg0_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_Block_entry13_proc1_U0_cfg0_s_din),
    .if_full_n(cfg0_s_full_n),
    .if_write(fft_Block_entry13_proc1_U0_cfg0_s_write),
    .if_dout(cfg0_s_dout),
    .if_num_data_valid(cfg0_s_num_data_valid),
    .if_fifo_cap(cfg0_s_fifo_cap),
    .if_empty_n(cfg0_s_empty_n),
    .if_read(fft_config1_1_U0_cfg0_s_read)
);

pfb_multichannel_fifo_w16_d2_S cfg1_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_Block_entry13_proc1_U0_cfg1_s_din),
    .if_full_n(cfg1_s_full_n),
    .if_write(fft_Block_entry13_proc1_U0_cfg1_s_write),
    .if_dout(cfg1_s_dout),
    .if_num_data_valid(cfg1_s_num_data_valid),
    .if_fifo_cap(cfg1_s_fifo_cap),
    .if_empty_n(cfg1_s_empty_n),
    .if_read(fft_config1_2_U0_cfg1_s_read)
);

pfb_multichannel_fifo_w16_d2_S cfg2_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_Block_entry13_proc1_U0_cfg2_s_din),
    .if_full_n(cfg2_s_full_n),
    .if_write(fft_Block_entry13_proc1_U0_cfg2_s_write),
    .if_dout(cfg2_s_dout),
    .if_num_data_valid(cfg2_s_num_data_valid),
    .if_fifo_cap(cfg2_s_fifo_cap),
    .if_empty_n(cfg2_s_empty_n),
    .if_read(fft_config1_3_U0_cfg2_s_read)
);

pfb_multichannel_fifo_w16_d2_S cfg3_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_Block_entry13_proc1_U0_cfg3_s_din),
    .if_full_n(cfg3_s_full_n),
    .if_write(fft_Block_entry13_proc1_U0_cfg3_s_write),
    .if_dout(cfg3_s_dout),
    .if_num_data_valid(cfg3_s_num_data_valid),
    .if_fifo_cap(cfg3_s_fifo_cap),
    .if_empty_n(cfg3_s_empty_n),
    .if_read(fft_config1_U0_cfg3_s_read)
);

pfb_multichannel_fifo_w32_d2_S ch0_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_1_U0_ch0_out_din),
    .if_full_n(ch0_out_full_n),
    .if_write(fft_config1_1_U0_ch0_out_write),
    .if_dout(ch0_out_dout),
    .if_num_data_valid(ch0_out_num_data_valid),
    .if_fifo_cap(ch0_out_fifo_cap),
    .if_empty_n(ch0_out_empty_n),
    .if_read(repack_U0_ch0_out_read)
);

pfb_multichannel_fifo_w8_d2_S stat0_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_1_U0_stat0_s_din),
    .if_full_n(stat0_s_full_n),
    .if_write(fft_config1_1_U0_stat0_s_write),
    .if_dout(stat0_s_dout),
    .if_num_data_valid(stat0_s_num_data_valid),
    .if_fifo_cap(stat0_s_fifo_cap),
    .if_empty_n(stat0_s_empty_n),
    .if_read(fft_Block_entry19_proc2_U0_stat0_s_read)
);

pfb_multichannel_fifo_w32_d2_S ch1_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_2_U0_ch1_out_din),
    .if_full_n(ch1_out_full_n),
    .if_write(fft_config1_2_U0_ch1_out_write),
    .if_dout(ch1_out_dout),
    .if_num_data_valid(ch1_out_num_data_valid),
    .if_fifo_cap(ch1_out_fifo_cap),
    .if_empty_n(ch1_out_empty_n),
    .if_read(repack_U0_ch1_out_read)
);

pfb_multichannel_fifo_w8_d2_S stat1_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_2_U0_stat1_s_din),
    .if_full_n(stat1_s_full_n),
    .if_write(fft_config1_2_U0_stat1_s_write),
    .if_dout(stat1_s_dout),
    .if_num_data_valid(stat1_s_num_data_valid),
    .if_fifo_cap(stat1_s_fifo_cap),
    .if_empty_n(stat1_s_empty_n),
    .if_read(fft_Block_entry19_proc2_U0_stat1_s_read)
);

pfb_multichannel_fifo_w32_d2_S ch2_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_3_U0_ch2_out_din),
    .if_full_n(ch2_out_full_n),
    .if_write(fft_config1_3_U0_ch2_out_write),
    .if_dout(ch2_out_dout),
    .if_num_data_valid(ch2_out_num_data_valid),
    .if_fifo_cap(ch2_out_fifo_cap),
    .if_empty_n(ch2_out_empty_n),
    .if_read(repack_U0_ch2_out_read)
);

pfb_multichannel_fifo_w8_d2_S stat2_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_3_U0_stat2_s_din),
    .if_full_n(stat2_s_full_n),
    .if_write(fft_config1_3_U0_stat2_s_write),
    .if_dout(stat2_s_dout),
    .if_num_data_valid(stat2_s_num_data_valid),
    .if_fifo_cap(stat2_s_fifo_cap),
    .if_empty_n(stat2_s_empty_n),
    .if_read(fft_Block_entry19_proc2_U0_stat2_s_read)
);

pfb_multichannel_fifo_w32_d2_S ch3_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_ch3_out_din),
    .if_full_n(ch3_out_full_n),
    .if_write(fft_config1_U0_ch3_out_write),
    .if_dout(ch3_out_dout),
    .if_num_data_valid(ch3_out_num_data_valid),
    .if_fifo_cap(ch3_out_fifo_cap),
    .if_empty_n(ch3_out_empty_n),
    .if_read(repack_U0_ch3_out_read)
);

pfb_multichannel_fifo_w8_d2_S stat3_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_stat3_s_din),
    .if_full_n(stat3_s_full_n),
    .if_write(fft_config1_U0_stat3_s_write),
    .if_dout(stat3_s_dout),
    .if_num_data_valid(stat3_s_num_data_valid),
    .if_fifo_cap(stat3_s_fifo_cap),
    .if_empty_n(stat3_s_empty_n),
    .if_read(fft_Block_entry19_proc2_U0_stat3_s_read)
);

pfb_multichannel_start_for_repack_U0 start_for_repack_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_repack_U0_din),
    .if_full_n(start_for_repack_U0_full_n),
    .if_write(unpack_U0_start_write),
    .if_dout(start_for_repack_U0_dout),
    .if_empty_n(start_for_repack_U0_empty_n),
    .if_read(repack_U0_ap_ready)
);

pfb_multichannel_start_for_fft_Block_entry19_proc2_U0 start_for_fft_Block_entry19_proc2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_Block_entry19_proc2_U0_din),
    .if_full_n(start_for_fft_Block_entry19_proc2_U0_full_n),
    .if_write(unpack_U0_start_write),
    .if_dout(start_for_fft_Block_entry19_proc2_U0_dout),
    .if_empty_n(start_for_fft_Block_entry19_proc2_U0_empty_n),
    .if_read(fft_Block_entry19_proc2_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready <= 1'b0;
    end else begin
        if (((real_start & ap_sync_ready) == 1'b1)) begin
            ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready <= ap_sync_fft_Block_entry13_proc1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_unpack_U0_ap_ready <= 1'b0;
    end else begin
        if (((real_start & ap_sync_ready) == 1'b1)) begin
            ap_sync_reg_unpack_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_unpack_U0_ap_ready <= ap_sync_unpack_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign ap_done = ap_sync_done;

assign ap_idle = (unpack_U0_ap_idle & repack_U0_ap_idle & fft_Block_entry19_proc2_U0_ap_idle & fft_Block_entry13_proc1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (repack_U0_ap_done & fft_Block_entry19_proc2_U0_ap_done);

assign ap_sync_fft_Block_entry13_proc1_U0_ap_ready = (fft_Block_entry13_proc1_U0_ap_ready | ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready);

assign ap_sync_ready = (ap_sync_unpack_U0_ap_ready & ap_sync_fft_Block_entry13_proc1_U0_ap_ready);

assign ap_sync_unpack_U0_ap_ready = (unpack_U0_ap_ready | ap_sync_reg_unpack_U0_ap_ready);

assign fft_Block_entry13_proc1_U0_ap_continue = 1'b1;

assign fft_Block_entry13_proc1_U0_ap_start = (real_start & (ap_sync_reg_fft_Block_entry13_proc1_U0_ap_ready ^ 1'b1));

assign fft_Block_entry19_proc2_U0_ap_continue = ap_sync_continue;

assign fft_Block_entry19_proc2_U0_ap_start = start_for_fft_Block_entry19_proc2_U0_empty_n;

assign internal_ap_ready = ap_sync_ready;

assign repack_U0_ap_continue = ap_sync_continue;

assign repack_U0_ap_start = start_for_repack_U0_empty_n;

assign start_for_fft_Block_entry19_proc2_U0_din = 1'b1;

assign start_for_repack_U0_din = 1'b1;

assign start_out = real_start;

assign stream_compute_to_fft_read = unpack_U0_stream_compute_to_fft_read;

assign stream_fft_to_write_din = repack_U0_stream_fft_to_write_din;

assign stream_fft_to_write_write = repack_U0_stream_fft_to_write_write;

assign unpack_U0_ap_continue = 1'b1;

assign unpack_U0_ap_start = (real_start & (ap_sync_reg_unpack_U0_ap_ready ^ 1'b1));

assign unpack_U0_start_full_n = (start_for_repack_U0_full_n & start_for_fft_Block_entry19_proc2_U0_full_n);

endmodule //pfb_multichannel_fft
