// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_fft_config1_s (
        ch3_in_dout,
        ch3_in_empty_n,
        ch3_in_read,
        ch3_out_din,
        ch3_out_full_n,
        ch3_out_write,
        stat3_s_din,
        stat3_s_full_n,
        stat3_s_write,
        cfg3_s_dout,
        cfg3_s_empty_n,
        cfg3_s_read,
        ap_clk,
        ap_rst,
        ap_ready
);


input  [31:0] ch3_in_dout;
input   ch3_in_empty_n;
output   ch3_in_read;
output  [31:0] ch3_out_din;
input   ch3_out_full_n;
output   ch3_out_write;
output  [7:0] stat3_s_din;
input   stat3_s_full_n;
output   stat3_s_write;
input  [15:0] cfg3_s_dout;
input   cfg3_s_empty_n;
output   cfg3_s_read;
input   ap_clk;
input   ap_rst;
output   ap_ready;

wire    fft_syn_config1_6_U0_ap_start;
wire    fft_syn_config1_6_U0_ap_done;
wire    fft_syn_config1_6_U0_ap_idle;
wire    fft_syn_config1_6_U0_ap_ready;
wire    fft_syn_config1_6_U0_ap_continue;
wire    fft_syn_config1_6_U0_xn_read;
wire   [31:0] fft_syn_config1_6_U0_xk_din;
wire    fft_syn_config1_6_U0_xk_write;
wire   [7:0] fft_syn_config1_6_U0_status_data_V_din;
wire    fft_syn_config1_6_U0_status_data_V_write;
wire    fft_syn_config1_6_U0_config_ch_data_V_read;

pfb_multichannel_fft_syn_config1_6 fft_syn_config1_6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(1'b1),
    .ap_start(fft_syn_config1_6_U0_ap_start),
    .ap_done(fft_syn_config1_6_U0_ap_done),
    .ap_idle(fft_syn_config1_6_U0_ap_idle),
    .ap_ready(fft_syn_config1_6_U0_ap_ready),
    .ap_continue(fft_syn_config1_6_U0_ap_continue),
    .xn_dout(ch3_in_dout),
    .xn_empty_n(ch3_in_empty_n),
    .xn_read(fft_syn_config1_6_U0_xn_read),
    .xk_din(fft_syn_config1_6_U0_xk_din),
    .xk_full_n(ch3_out_full_n),
    .xk_write(fft_syn_config1_6_U0_xk_write),
    .status_data_V_din(fft_syn_config1_6_U0_status_data_V_din),
    .status_data_V_full_n(stat3_s_full_n),
    .status_data_V_write(fft_syn_config1_6_U0_status_data_V_write),
    .config_ch_data_V_dout(cfg3_s_dout),
    .config_ch_data_V_empty_n(cfg3_s_empty_n),
    .config_ch_data_V_read(fft_syn_config1_6_U0_config_ch_data_V_read)
);

assign ap_ready = 1'b1;

assign cfg3_s_read = fft_syn_config1_6_U0_config_ch_data_V_read;

assign ch3_in_read = fft_syn_config1_6_U0_xn_read;

assign ch3_out_din = fft_syn_config1_6_U0_xk_din;

assign ch3_out_write = fft_syn_config1_6_U0_xk_write;

assign fft_syn_config1_6_U0_ap_continue = 1'b1;

assign fft_syn_config1_6_U0_ap_start = 1'b1;

assign stat3_s_din = fft_syn_config1_6_U0_status_data_V_din;

assign stat3_s_write = fft_syn_config1_6_U0_status_data_V_write;

endmodule //pfb_multichannel_fft_config1_s
