// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_fft_Block_entry19_proc2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stat0_s_dout,
        stat0_s_num_data_valid,
        stat0_s_fifo_cap,
        stat0_s_empty_n,
        stat0_s_read,
        stat1_s_dout,
        stat1_s_num_data_valid,
        stat1_s_fifo_cap,
        stat1_s_empty_n,
        stat1_s_read,
        stat2_s_dout,
        stat2_s_num_data_valid,
        stat2_s_fifo_cap,
        stat2_s_empty_n,
        stat2_s_read,
        stat3_s_dout,
        stat3_s_num_data_valid,
        stat3_s_fifo_cap,
        stat3_s_empty_n,
        stat3_s_read
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] stat0_s_dout;
input  [2:0] stat0_s_num_data_valid;
input  [2:0] stat0_s_fifo_cap;
input   stat0_s_empty_n;
output   stat0_s_read;
input  [7:0] stat1_s_dout;
input  [2:0] stat1_s_num_data_valid;
input  [2:0] stat1_s_fifo_cap;
input   stat1_s_empty_n;
output   stat1_s_read;
input  [7:0] stat2_s_dout;
input  [2:0] stat2_s_num_data_valid;
input  [2:0] stat2_s_fifo_cap;
input   stat2_s_empty_n;
output   stat2_s_read;
input  [7:0] stat3_s_dout;
input  [2:0] stat3_s_num_data_valid;
input  [2:0] stat3_s_fifo_cap;
input   stat3_s_empty_n;
output   stat3_s_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stat0_s_read;
reg stat1_s_read;
reg stat2_s_read;
reg stat3_s_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    stat0_s_blk_n;
reg    stat1_s_blk_n;
reg    stat2_s_blk_n;
reg    stat3_s_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        stat0_s_blk_n = stat0_s_empty_n;
    end else begin
        stat0_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        stat0_s_read = 1'b1;
    end else begin
        stat0_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        stat1_s_blk_n = stat1_s_empty_n;
    end else begin
        stat1_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        stat1_s_read = 1'b1;
    end else begin
        stat1_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        stat2_s_blk_n = stat2_s_empty_n;
    end else begin
        stat2_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        stat2_s_read = 1'b1;
    end else begin
        stat2_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        stat3_s_blk_n = stat3_s_empty_n;
    end else begin
        stat3_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        stat3_s_read = 1'b1;
    end else begin
        stat3_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (stat3_s_empty_n == 1'b0) | (stat2_s_empty_n == 1'b0) | (stat1_s_empty_n == 1'b0) | (stat0_s_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

endmodule //pfb_multichannel_fft_Block_entry19_proc2
