// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_read_inputs (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        din_data_i0_TDATA,
        din_data_i0_TVALID,
        din_data_i0_TREADY,
        din_data_q0_TDATA,
        din_data_q0_TVALID,
        din_data_q0_TREADY,
        din_data_i1_TDATA,
        din_data_i1_TVALID,
        din_data_i1_TREADY,
        din_data_q1_TDATA,
        din_data_q1_TVALID,
        din_data_q1_TREADY,
        din_data_i2_TDATA,
        din_data_i2_TVALID,
        din_data_i2_TREADY,
        din_data_q2_TDATA,
        din_data_q2_TVALID,
        din_data_q2_TREADY,
        din_data_i3_TDATA,
        din_data_i3_TVALID,
        din_data_i3_TREADY,
        din_data_q3_TDATA,
        din_data_q3_TVALID,
        din_data_q3_TREADY,
        stream_read_to_compute_din,
        stream_read_to_compute_num_data_valid,
        stream_read_to_compute_fifo_cap,
        stream_read_to_compute_full_n,
        stream_read_to_compute_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] din_data_i0_TDATA;
input   din_data_i0_TVALID;
output   din_data_i0_TREADY;
input  [15:0] din_data_q0_TDATA;
input   din_data_q0_TVALID;
output   din_data_q0_TREADY;
input  [15:0] din_data_i1_TDATA;
input   din_data_i1_TVALID;
output   din_data_i1_TREADY;
input  [15:0] din_data_q1_TDATA;
input   din_data_q1_TVALID;
output   din_data_q1_TREADY;
input  [15:0] din_data_i2_TDATA;
input   din_data_i2_TVALID;
output   din_data_i2_TREADY;
input  [15:0] din_data_q2_TDATA;
input   din_data_q2_TVALID;
output   din_data_q2_TREADY;
input  [15:0] din_data_i3_TDATA;
input   din_data_i3_TVALID;
output   din_data_i3_TREADY;
input  [15:0] din_data_q3_TDATA;
input   din_data_q3_TVALID;
output   din_data_q3_TREADY;
output  [127:0] stream_read_to_compute_din;
input  [4:0] stream_read_to_compute_num_data_valid;
input  [4:0] stream_read_to_compute_fifo_cap;
input   stream_read_to_compute_full_n;
output   stream_read_to_compute_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_read_to_compute_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] dummy_state_3;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_ap_start;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_ap_done;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_ap_idle;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_ap_ready;
wire   [127:0] grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_din;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY;
wire    grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY;
reg    grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [31:0] add_ln15_fu_68_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    regslice_both_din_data_i0_U_apdone_blk;
wire   [15:0] din_data_i0_TDATA_int_regslice;
wire    din_data_i0_TVALID_int_regslice;
reg    din_data_i0_TREADY_int_regslice;
wire    regslice_both_din_data_i0_U_ack_in;
wire    regslice_both_din_data_q0_U_apdone_blk;
wire   [15:0] din_data_q0_TDATA_int_regslice;
wire    din_data_q0_TVALID_int_regslice;
reg    din_data_q0_TREADY_int_regslice;
wire    regslice_both_din_data_q0_U_ack_in;
wire    regslice_both_din_data_i1_U_apdone_blk;
wire   [15:0] din_data_i1_TDATA_int_regslice;
wire    din_data_i1_TVALID_int_regslice;
reg    din_data_i1_TREADY_int_regslice;
wire    regslice_both_din_data_i1_U_ack_in;
wire    regslice_both_din_data_q1_U_apdone_blk;
wire   [15:0] din_data_q1_TDATA_int_regslice;
wire    din_data_q1_TVALID_int_regslice;
reg    din_data_q1_TREADY_int_regslice;
wire    regslice_both_din_data_q1_U_ack_in;
wire    regslice_both_din_data_i2_U_apdone_blk;
wire   [15:0] din_data_i2_TDATA_int_regslice;
wire    din_data_i2_TVALID_int_regslice;
reg    din_data_i2_TREADY_int_regslice;
wire    regslice_both_din_data_i2_U_ack_in;
wire    regslice_both_din_data_q2_U_apdone_blk;
wire   [15:0] din_data_q2_TDATA_int_regslice;
wire    din_data_q2_TVALID_int_regslice;
reg    din_data_q2_TREADY_int_regslice;
wire    regslice_both_din_data_q2_U_ack_in;
wire    regslice_both_din_data_i3_U_apdone_blk;
wire   [15:0] din_data_i3_TDATA_int_regslice;
wire    din_data_i3_TVALID_int_regslice;
reg    din_data_i3_TREADY_int_regslice;
wire    regslice_both_din_data_i3_U_ack_in;
wire    regslice_both_din_data_q3_U_apdone_blk;
wire   [15:0] din_data_q3_TDATA_int_regslice;
wire    din_data_q3_TVALID_int_regslice;
reg    din_data_q3_TREADY_int_regslice;
wire    regslice_both_din_data_q3_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 dummy_state_3 = 32'd0;
#0 grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg = 1'b0;
end

pfb_multichannel_read_inputs_Pipeline_read_loop grp_read_inputs_Pipeline_read_loop_fu_42(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_read_inputs_Pipeline_read_loop_fu_42_ap_start),
    .ap_done(grp_read_inputs_Pipeline_read_loop_fu_42_ap_done),
    .ap_idle(grp_read_inputs_Pipeline_read_loop_fu_42_ap_idle),
    .ap_ready(grp_read_inputs_Pipeline_read_loop_fu_42_ap_ready),
    .din_data_i0_TVALID(din_data_i0_TVALID_int_regslice),
    .din_data_q0_TVALID(din_data_q0_TVALID_int_regslice),
    .din_data_i1_TVALID(din_data_i1_TVALID_int_regslice),
    .din_data_q1_TVALID(din_data_q1_TVALID_int_regslice),
    .din_data_i2_TVALID(din_data_i2_TVALID_int_regslice),
    .din_data_q2_TVALID(din_data_q2_TVALID_int_regslice),
    .din_data_i3_TVALID(din_data_i3_TVALID_int_regslice),
    .din_data_q3_TVALID(din_data_q3_TVALID_int_regslice),
    .stream_read_to_compute_din(grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_din),
    .stream_read_to_compute_num_data_valid(5'd0),
    .stream_read_to_compute_fifo_cap(5'd0),
    .stream_read_to_compute_full_n(stream_read_to_compute_full_n),
    .stream_read_to_compute_write(grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write),
    .din_data_i0_TDATA(din_data_i0_TDATA_int_regslice),
    .din_data_i0_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY),
    .din_data_q0_TDATA(din_data_q0_TDATA_int_regslice),
    .din_data_q0_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY),
    .din_data_i1_TDATA(din_data_i1_TDATA_int_regslice),
    .din_data_i1_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY),
    .din_data_q1_TDATA(din_data_q1_TDATA_int_regslice),
    .din_data_q1_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY),
    .din_data_i2_TDATA(din_data_i2_TDATA_int_regslice),
    .din_data_i2_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY),
    .din_data_q2_TDATA(din_data_q2_TDATA_int_regslice),
    .din_data_q2_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY),
    .din_data_i3_TDATA(din_data_i3_TDATA_int_regslice),
    .din_data_i3_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY),
    .din_data_q3_TDATA(din_data_q3_TDATA_int_regslice),
    .din_data_q3_TREADY(grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i0_TDATA),
    .vld_in(din_data_i0_TVALID),
    .ack_in(regslice_both_din_data_i0_U_ack_in),
    .data_out(din_data_i0_TDATA_int_regslice),
    .vld_out(din_data_i0_TVALID_int_regslice),
    .ack_out(din_data_i0_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i0_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q0_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q0_TDATA),
    .vld_in(din_data_q0_TVALID),
    .ack_in(regslice_both_din_data_q0_U_ack_in),
    .data_out(din_data_q0_TDATA_int_regslice),
    .vld_out(din_data_q0_TVALID_int_regslice),
    .ack_out(din_data_q0_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q0_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i1_TDATA),
    .vld_in(din_data_i1_TVALID),
    .ack_in(regslice_both_din_data_i1_U_ack_in),
    .data_out(din_data_i1_TDATA_int_regslice),
    .vld_out(din_data_i1_TVALID_int_regslice),
    .ack_out(din_data_i1_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i1_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q1_TDATA),
    .vld_in(din_data_q1_TVALID),
    .ack_in(regslice_both_din_data_q1_U_ack_in),
    .data_out(din_data_q1_TDATA_int_regslice),
    .vld_out(din_data_q1_TVALID_int_regslice),
    .ack_out(din_data_q1_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q1_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i2_TDATA),
    .vld_in(din_data_i2_TVALID),
    .ack_in(regslice_both_din_data_i2_U_ack_in),
    .data_out(din_data_i2_TDATA_int_regslice),
    .vld_out(din_data_i2_TVALID_int_regslice),
    .ack_out(din_data_i2_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i2_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q2_TDATA),
    .vld_in(din_data_q2_TVALID),
    .ack_in(regslice_both_din_data_q2_U_ack_in),
    .data_out(din_data_q2_TDATA_int_regslice),
    .vld_out(din_data_q2_TVALID_int_regslice),
    .ack_out(din_data_q2_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q2_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_i3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_i3_TDATA),
    .vld_in(din_data_i3_TVALID),
    .ack_in(regslice_both_din_data_i3_U_ack_in),
    .data_out(din_data_i3_TDATA_int_regslice),
    .vld_out(din_data_i3_TVALID_int_regslice),
    .ack_out(din_data_i3_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_i3_U_apdone_blk)
);

pfb_multichannel_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_data_q3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_data_q3_TDATA),
    .vld_in(din_data_q3_TVALID),
    .ack_in(regslice_both_din_data_q3_U_ack_in),
    .data_out(din_data_q3_TDATA_int_regslice),
    .vld_out(din_data_q3_TVALID_int_regslice),
    .ack_out(din_data_q3_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_data_q3_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg <= 1'b1;
        end else if ((grp_read_inputs_Pipeline_read_loop_fu_42_ap_ready == 1'b1)) begin
            grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        dummy_state_3 <= add_ln15_fu_68_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_i0_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i0_TREADY;
    end else begin
        din_data_i0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_i1_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i1_TREADY;
    end else begin
        din_data_i1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_i2_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i2_TREADY;
    end else begin
        din_data_i2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_i3_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_i3_TREADY;
    end else begin
        din_data_i3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_q0_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q0_TREADY;
    end else begin
        din_data_q0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_q1_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q1_TREADY;
    end else begin
        din_data_q1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_q2_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q2_TREADY;
    end else begin
        din_data_q2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        din_data_q3_TREADY_int_regslice = grp_read_inputs_Pipeline_read_loop_fu_42_din_data_q3_TREADY;
    end else begin
        din_data_q3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_read_to_compute_write = grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_write;
    end else begin
        stream_read_to_compute_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_read_inputs_Pipeline_read_loop_fu_42_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_68_p2 = (dummy_state_3 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign din_data_i0_TREADY = regslice_both_din_data_i0_U_ack_in;

assign din_data_i1_TREADY = regslice_both_din_data_i1_U_ack_in;

assign din_data_i2_TREADY = regslice_both_din_data_i2_U_ack_in;

assign din_data_i3_TREADY = regslice_both_din_data_i3_U_ack_in;

assign din_data_q0_TREADY = regslice_both_din_data_q0_U_ack_in;

assign din_data_q1_TREADY = regslice_both_din_data_q1_U_ack_in;

assign din_data_q2_TREADY = regslice_both_din_data_q2_U_ack_in;

assign din_data_q3_TREADY = regslice_both_din_data_q3_U_ack_in;

assign grp_read_inputs_Pipeline_read_loop_fu_42_ap_start = grp_read_inputs_Pipeline_read_loop_fu_42_ap_start_reg;

assign stream_read_to_compute_din = grp_read_inputs_Pipeline_read_loop_fu_42_stream_read_to_compute_din;

endmodule //pfb_multichannel_read_inputs
