// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_write_outputs_Pipeline_write_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_fft_to_write_dout,
        stream_fft_to_write_num_data_valid,
        stream_fft_to_write_fifo_cap,
        stream_fft_to_write_empty_n,
        stream_fft_to_write_read,
        dout_data_0_TREADY,
        dout_data_1_TREADY,
        dout_data_2_TREADY,
        dout_data_3_TREADY,
        dout_data_0_TDATA,
        dout_data_0_TVALID,
        dout_data_1_TDATA,
        dout_data_1_TVALID,
        dout_data_2_TDATA,
        dout_data_2_TVALID,
        dout_data_3_TDATA,
        dout_data_3_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] stream_fft_to_write_dout;
input  [4:0] stream_fft_to_write_num_data_valid;
input  [4:0] stream_fft_to_write_fifo_cap;
input   stream_fft_to_write_empty_n;
output   stream_fft_to_write_read;
input   dout_data_0_TREADY;
input   dout_data_1_TREADY;
input   dout_data_2_TREADY;
input   dout_data_3_TREADY;
output  [31:0] dout_data_0_TDATA;
output   dout_data_0_TVALID;
output  [31:0] dout_data_1_TDATA;
output   dout_data_1_TVALID;
output  [31:0] dout_data_2_TDATA;
output   dout_data_2_TVALID;
output  [31:0] dout_data_3_TDATA;
output   dout_data_3_TVALID;

reg ap_idle;
reg stream_fft_to_write_read;
reg dout_data_0_TVALID;
reg dout_data_1_TVALID;
reg dout_data_2_TVALID;
reg dout_data_3_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_124_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_fft_to_write_blk_n;
wire    ap_block_pp0_stage0;
reg    dout_data_0_TDATA_blk_n;
reg    dout_data_1_TDATA_blk_n;
reg    dout_data_2_TDATA_blk_n;
reg    dout_data_3_TDATA_blk_n;
reg   [10:0] i_fu_78;
wire   [10:0] i_2_fu_130_p2;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_11001;
reg   [10:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] pack_i_fu_141_p1;
wire   [15:0] trunc_ln50_2_fu_145_p4;
wire   [15:0] trunc_ln50_3_fu_155_p4;
wire   [15:0] trunc_ln50_4_fu_165_p4;
wire   [15:0] trunc_ln50_5_fu_175_p4;
wire   [15:0] trunc_ln50_6_fu_185_p4;
wire   [15:0] trunc_ln50_7_fu_195_p4;
wire   [15:0] trunc_ln50_8_fu_205_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_78 = 11'd0;
#0 ap_done_reg = 1'b0;
end

pfb_multichannel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_124_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_78 <= i_2_fu_130_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_78 <= 11'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_124_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_0_TDATA_blk_n = dout_data_0_TREADY;
    end else begin
        dout_data_0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_0_TVALID = 1'b1;
    end else begin
        dout_data_0_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_1_TDATA_blk_n = dout_data_1_TREADY;
    end else begin
        dout_data_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_1_TVALID = 1'b1;
    end else begin
        dout_data_1_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_2_TDATA_blk_n = dout_data_2_TREADY;
    end else begin
        dout_data_2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_2_TVALID = 1'b1;
    end else begin
        dout_data_2_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_3_TDATA_blk_n = dout_data_3_TREADY;
    end else begin
        dout_data_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dout_data_3_TVALID = 1'b1;
    end else begin
        dout_data_3_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_fft_to_write_blk_n = stream_fft_to_write_empty_n;
    end else begin
        stream_fft_to_write_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_fft_to_write_read = 1'b1;
    end else begin
        stream_fft_to_write_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_io = ((dout_data_3_TREADY == 1'b0) | (dout_data_2_TREADY == 1'b0) | (dout_data_1_TREADY == 1'b0) | (dout_data_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((dout_data_3_TREADY == 1'b0) | (dout_data_2_TREADY == 1'b0) | (dout_data_1_TREADY == 1'b0) | (dout_data_0_TREADY == 1'b0) | (stream_fft_to_write_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign dout_data_0_TDATA = {{pack_i_fu_141_p1}, {trunc_ln50_2_fu_145_p4}};

assign dout_data_1_TDATA = {{trunc_ln50_3_fu_155_p4}, {trunc_ln50_4_fu_165_p4}};

assign dout_data_2_TDATA = {{trunc_ln50_5_fu_175_p4}, {trunc_ln50_6_fu_185_p4}};

assign dout_data_3_TDATA = {{trunc_ln50_7_fu_195_p4}, {trunc_ln50_8_fu_205_p4}};

assign i_2_fu_130_p2 = (ap_sig_allocacmp_i_1 + 11'd1);

assign icmp_ln47_fu_124_p2 = ((ap_sig_allocacmp_i_1 == 11'd1024) ? 1'b1 : 1'b0);

assign pack_i_fu_141_p1 = stream_fft_to_write_dout[15:0];

assign trunc_ln50_2_fu_145_p4 = {{stream_fft_to_write_dout[31:16]}};

assign trunc_ln50_3_fu_155_p4 = {{stream_fft_to_write_dout[47:32]}};

assign trunc_ln50_4_fu_165_p4 = {{stream_fft_to_write_dout[63:48]}};

assign trunc_ln50_5_fu_175_p4 = {{stream_fft_to_write_dout[79:64]}};

assign trunc_ln50_6_fu_185_p4 = {{stream_fft_to_write_dout[95:80]}};

assign trunc_ln50_7_fu_195_p4 = {{stream_fft_to_write_dout[111:96]}};

assign trunc_ln50_8_fu_205_p4 = {{stream_fft_to_write_dout[127:112]}};

endmodule //pfb_multichannel_write_outputs_Pipeline_write_loop
