// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pfb_multichannel_repack (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ch0_out_dout,
        ch0_out_num_data_valid,
        ch0_out_fifo_cap,
        ch0_out_empty_n,
        ch0_out_read,
        ch1_out_dout,
        ch1_out_num_data_valid,
        ch1_out_fifo_cap,
        ch1_out_empty_n,
        ch1_out_read,
        ch2_out_dout,
        ch2_out_num_data_valid,
        ch2_out_fifo_cap,
        ch2_out_empty_n,
        ch2_out_read,
        ch3_out_dout,
        ch3_out_num_data_valid,
        ch3_out_fifo_cap,
        ch3_out_empty_n,
        ch3_out_read,
        stream_fft_to_write_din,
        stream_fft_to_write_num_data_valid,
        stream_fft_to_write_fifo_cap,
        stream_fft_to_write_full_n,
        stream_fft_to_write_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] ch0_out_dout;
input  [10:0] ch0_out_num_data_valid;
input  [10:0] ch0_out_fifo_cap;
input   ch0_out_empty_n;
output   ch0_out_read;
input  [31:0] ch1_out_dout;
input  [10:0] ch1_out_num_data_valid;
input  [10:0] ch1_out_fifo_cap;
input   ch1_out_empty_n;
output   ch1_out_read;
input  [31:0] ch2_out_dout;
input  [10:0] ch2_out_num_data_valid;
input  [10:0] ch2_out_fifo_cap;
input   ch2_out_empty_n;
output   ch2_out_read;
input  [31:0] ch3_out_dout;
input  [10:0] ch3_out_num_data_valid;
input  [10:0] ch3_out_fifo_cap;
input   ch3_out_empty_n;
output   ch3_out_read;
output  [127:0] stream_fft_to_write_din;
input  [4:0] stream_fft_to_write_num_data_valid;
input  [4:0] stream_fft_to_write_fifo_cap;
input   stream_fft_to_write_full_n;
output   stream_fft_to_write_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ch0_out_read;
reg ch1_out_read;
reg ch2_out_read;
reg ch3_out_read;
reg stream_fft_to_write_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] dummy_state_2;
wire    grp_repack_Pipeline_repack_loop_fu_30_ap_start;
wire    grp_repack_Pipeline_repack_loop_fu_30_ap_done;
wire    grp_repack_Pipeline_repack_loop_fu_30_ap_idle;
wire    grp_repack_Pipeline_repack_loop_fu_30_ap_ready;
wire    grp_repack_Pipeline_repack_loop_fu_30_ch0_out_read;
wire    grp_repack_Pipeline_repack_loop_fu_30_ch1_out_read;
wire    grp_repack_Pipeline_repack_loop_fu_30_ch2_out_read;
wire    grp_repack_Pipeline_repack_loop_fu_30_ch3_out_read;
wire   [127:0] grp_repack_Pipeline_repack_loop_fu_30_stream_fft_to_write_din;
wire    grp_repack_Pipeline_repack_loop_fu_30_stream_fft_to_write_write;
reg    grp_repack_Pipeline_repack_loop_fu_30_ap_start_reg;
reg    ap_block_state1_ignore_call10;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln107_fu_48_p2;
reg    ap_block_state1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 dummy_state_2 = 32'd0;
#0 grp_repack_Pipeline_repack_loop_fu_30_ap_start_reg = 1'b0;
end

pfb_multichannel_repack_Pipeline_repack_loop grp_repack_Pipeline_repack_loop_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_repack_Pipeline_repack_loop_fu_30_ap_start),
    .ap_done(grp_repack_Pipeline_repack_loop_fu_30_ap_done),
    .ap_idle(grp_repack_Pipeline_repack_loop_fu_30_ap_idle),
    .ap_ready(grp_repack_Pipeline_repack_loop_fu_30_ap_ready),
    .ch0_out_dout(ch0_out_dout),
    .ch0_out_num_data_valid(11'd0),
    .ch0_out_fifo_cap(11'd0),
    .ch0_out_empty_n(ch0_out_empty_n),
    .ch0_out_read(grp_repack_Pipeline_repack_loop_fu_30_ch0_out_read),
    .ch1_out_dout(ch1_out_dout),
    .ch1_out_num_data_valid(11'd0),
    .ch1_out_fifo_cap(11'd0),
    .ch1_out_empty_n(ch1_out_empty_n),
    .ch1_out_read(grp_repack_Pipeline_repack_loop_fu_30_ch1_out_read),
    .ch2_out_dout(ch2_out_dout),
    .ch2_out_num_data_valid(11'd0),
    .ch2_out_fifo_cap(11'd0),
    .ch2_out_empty_n(ch2_out_empty_n),
    .ch2_out_read(grp_repack_Pipeline_repack_loop_fu_30_ch2_out_read),
    .ch3_out_dout(ch3_out_dout),
    .ch3_out_num_data_valid(11'd0),
    .ch3_out_fifo_cap(11'd0),
    .ch3_out_empty_n(ch3_out_empty_n),
    .ch3_out_read(grp_repack_Pipeline_repack_loop_fu_30_ch3_out_read),
    .stream_fft_to_write_din(grp_repack_Pipeline_repack_loop_fu_30_stream_fft_to_write_din),
    .stream_fft_to_write_num_data_valid(5'd0),
    .stream_fft_to_write_fifo_cap(5'd0),
    .stream_fft_to_write_full_n(stream_fft_to_write_full_n),
    .stream_fft_to_write_write(grp_repack_Pipeline_repack_loop_fu_30_stream_fft_to_write_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_repack_Pipeline_repack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_repack_Pipeline_repack_loop_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call10) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_repack_Pipeline_repack_loop_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_repack_Pipeline_repack_loop_fu_30_ap_ready == 1'b1)) begin
            grp_repack_Pipeline_repack_loop_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        dummy_state_2 <= add_ln107_fu_48_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_repack_Pipeline_repack_loop_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_repack_Pipeline_repack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_repack_Pipeline_repack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch0_out_read = grp_repack_Pipeline_repack_loop_fu_30_ch0_out_read;
    end else begin
        ch0_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch1_out_read = grp_repack_Pipeline_repack_loop_fu_30_ch1_out_read;
    end else begin
        ch1_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch2_out_read = grp_repack_Pipeline_repack_loop_fu_30_ch2_out_read;
    end else begin
        ch2_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ch3_out_read = grp_repack_Pipeline_repack_loop_fu_30_ch3_out_read;
    end else begin
        ch3_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        stream_fft_to_write_write = grp_repack_Pipeline_repack_loop_fu_30_stream_fft_to_write_write;
    end else begin
        stream_fft_to_write_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_repack_Pipeline_repack_loop_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln107_fu_48_p2 = (dummy_state_2 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_repack_Pipeline_repack_loop_fu_30_ap_start = grp_repack_Pipeline_repack_loop_fu_30_ap_start_reg;

assign stream_fft_to_write_din = grp_repack_Pipeline_repack_loop_fu_30_stream_fft_to_write_din;

endmodule //pfb_multichannel_repack
